project:
  type: website
  output-dir: docs

website:
  title: MMCP
  page-navigation: true
  page-footer: 
   left: "Copyright 2023, Nicola Righetti"
   right: 
     - icon: wordpress
       href: https://www.nicolarighetti.net
     - icon: github
       href: https://github.com/nicolarighetti
     - icon: mastodon 
       href: https://mas.to/@nicolarighetti
     - icon: linkedin
       href: https://www.linkedin.com/in/nicolarighetti79/
  navbar:
   background: primary
   search: true
   left:
     - text: Home
       file: index.qmd
     - text: "Introduction"
       file: introduction.qmd
     - text: "R"
       file: Rintro.qmd
     - text: "EDA"
       file: EDA.qmd
     - text: "Regression"
       file: regression.qmd
     - text: "Mediation"
       file: mediation.qmd
     - text: "Moderation"
       file: moderation.qmd
     - text: "Conditional"
       file: conditional.qmd

  sidebar:
       style: "docked"
       search: true
       background: light
       collapse-level: 2
       contents:
        - section: "Introduction"
          contents: introduction.qmd
          href: introduction.qmd
        - section: "Getting started with R"
          contents: Rintro.qmd
          href: Rintro.qmd
        - section: "Exploratory Data Analysis"
          contents: EDA.qmd
          href: EDA.qmd
        - section: "Regression Analysis"
          contents: regression.qmd
          href: regression.qmd
        - section: "Mediation Analysis"
          contents: mediation.qmd
          href: mediation.qmd
        - section: "Moderation Analysis"
          contents: moderation.qmd
          href: moderation.qmd
        - section: "Conditional Process Analysis"
          contents: conditional.qmd
          href: conditional.qmd
         
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

