<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Nicola Righetti, PhD">

<title>Mediation, Moderation, and Conditional Process Analysis with R - Conditional process</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="//conditional.html" rel="next">
<link href="//moderation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="site_libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="site_libs/viz-1.8.2/viz.js"></script>
<link href="site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="site_libs/grViz-binding-1.0.9/grViz.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Mediation, Moderation, and Conditional Process Analysis with R</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./introduction.html" aria-current="page">
 <span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Rintro.html">
 <span class="menu-text">R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./EDA.html">
 <span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./regression.html">
 <span class="menu-text">Regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mediation.html">
 <span class="menu-text">Mediation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./moderation.html">
 <span class="menu-text">Moderation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conditional.html">
 <span class="menu-text">Conditional</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Conditional process</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction.html" class="sidebar-item-text sidebar-link">Introduction</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Rintro.html" class="sidebar-item-text sidebar-link">Getting started with R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./EDA.html" class="sidebar-item-text sidebar-link">Exploratory Data Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression.html" class="sidebar-item-text sidebar-link">Regression Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mediation.html" class="sidebar-item-text sidebar-link">Mediation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./moderation.html" class="sidebar-item-text sidebar-link">Moderation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./conditional.html" class="sidebar-item-text sidebar-link active">Conditional Process Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#the-concept-of-conditional-process" id="toc-the-concept-of-conditional-process" class="nav-link" data-scroll-target="#the-concept-of-conditional-process">The concept of conditional process</a>
  <ul class="collapse">
  <li><a href="#conceptual-diagram" id="toc-conceptual-diagram" class="nav-link" data-scroll-target="#conceptual-diagram">Conceptual diagram</a></li>
  <li><a href="#types-of-conditional-process" id="toc-types-of-conditional-process" class="nav-link" data-scroll-target="#types-of-conditional-process">Types of conditional process</a></li>
  <li><a href="#recap-of-direct-and-indirect-effects" id="toc-recap-of-direct-and-indirect-effects" class="nav-link" data-scroll-target="#recap-of-direct-and-indirect-effects">Recap of direct and indirect effects</a></li>
  <li><a href="#recap-of-conditional-effects" id="toc-recap-of-conditional-effects" class="nav-link" data-scroll-target="#recap-of-conditional-effects">Recap of conditional effects</a></li>
  </ul></li>
  <li><a href="#conditional-indirectdirect-effect" id="toc-conditional-indirectdirect-effect" class="nav-link" data-scroll-target="#conditional-indirectdirect-effect">Conditional indirect/direct effect</a>
  <ul class="collapse">
  <li><a href="#conditional-direct-effect" id="toc-conditional-direct-effect" class="nav-link" data-scroll-target="#conditional-direct-effect">Conditional direct effect</a></li>
  <li><a href="#conditional-indirect-effect" id="toc-conditional-indirect-effect" class="nav-link" data-scroll-target="#conditional-indirect-effect">Conditional indirect effect</a></li>
  </ul></li>
  <li><a href="#moderation-of-a-specific-indirect-effect-in-a-parallel-multiple-mediator-model" id="toc-moderation-of-a-specific-indirect-effect-in-a-parallel-multiple-mediator-model" class="nav-link" data-scroll-target="#moderation-of-a-specific-indirect-effect-in-a-parallel-multiple-mediator-model">Moderation of a specific indirect effect in a parallel multiple mediator model</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  </ul></li>
  <li><a href="#conditional-indirect-effect-model-with-process" id="toc-conditional-indirect-effect-model-with-process" class="nav-link" data-scroll-target="#conditional-indirect-effect-model-with-process">Conditional indirect effect model with process</a>
  <ul class="collapse">
  <li><a href="#conditional-indirect-effect-1" id="toc-conditional-indirect-effect-1" class="nav-link" data-scroll-target="#conditional-indirect-effect-1">Conditional indirect effect</a>
  <ul class="collapse">
  <li><a href="#conditional-effect" id="toc-conditional-effect" class="nav-link" data-scroll-target="#conditional-effect">Conditional effect</a></li>
  <li><a href="#conditional-indirect-effect-2" id="toc-conditional-indirect-effect-2" class="nav-link" data-scroll-target="#conditional-indirect-effect-2">Conditional indirect effect</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#visualize-the-conditional-effect" id="toc-visualize-the-conditional-effect" class="nav-link" data-scroll-target="#visualize-the-conditional-effect">Visualize the conditional effect</a></li>
  <li><a href="#conditional-effect-1" id="toc-conditional-effect-1" class="nav-link" data-scroll-target="#conditional-effect-1">Conditional effect</a></li>
  <li><a href="#other-regression-coefficients" id="toc-other-regression-coefficients" class="nav-link" data-scroll-target="#other-regression-coefficients">Other regression coefficients</a></li>
  <li><a href="#conditional-direct-and-indirect-effect-model-with-process" id="toc-conditional-direct-and-indirect-effect-model-with-process" class="nav-link" data-scroll-target="#conditional-direct-and-indirect-effect-model-with-process">Conditional direct and indirect effect model with process</a></li>
  <li><a href="#conditional-process-analysis-with-multicategorical-antecedent" id="toc-conditional-process-analysis-with-multicategorical-antecedent" class="nav-link" data-scroll-target="#conditional-process-analysis-with-multicategorical-antecedent">Conditional process analysis with multicategorical antecedent</a>
  <ul class="collapse">
  <li><a href="#brief-recap-on-the-interpretation-of-multicategorical-variables" id="toc-brief-recap-on-the-interpretation-of-multicategorical-variables" class="nav-link" data-scroll-target="#brief-recap-on-the-interpretation-of-multicategorical-variables">Brief recap on the interpretation of multicategorical variables</a></li>
  </ul></li>
  <li><a href="#relative-conditional-effect" id="toc-relative-conditional-effect" class="nav-link" data-scroll-target="#relative-conditional-effect">Relative conditional effect</a></li>
  <li><a href="#conditional-direct-and-indirect-relative-effects" id="toc-conditional-direct-and-indirect-relative-effects" class="nav-link" data-scroll-target="#conditional-direct-and-indirect-relative-effects">Conditional direct and indirect relative effects</a></li>
  <li><a href="#appendix-assumptions-and-robust-methods" id="toc-appendix-assumptions-and-robust-methods" class="nav-link" data-scroll-target="#appendix-assumptions-and-robust-methods">Appendix: Assumptions and robust methods</a>
  <ul class="collapse">
  <li><a href="#check-the-assumptions" id="toc-check-the-assumptions" class="nav-link" data-scroll-target="#check-the-assumptions">Check the assumptions</a></li>
  <li><a href="#check-regression-assumptions" id="toc-check-regression-assumptions" class="nav-link" data-scroll-target="#check-regression-assumptions">Check regression assumptions</a></li>
  <li><a href="#custom-models" id="toc-custom-models" class="nav-link" data-scroll-target="#custom-models">Custom models</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Conditional process</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Nicola Righetti, PhD </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="learning-goals" class="level1">
<h1>Learning goals</h1>
<ul>
<li>Learning the concept of conditional process with particular attention to conditional direct and indirect effects, and relative conditional direct and indirect effects.</li>
<li>Learn to fit conditional process models.</li>
<li>Learn to interpret the output of conditional process models.</li>
<li>Learn how to test regression assumptions.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-718214b6e0522b109da0" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-718214b6e0522b109da0">{"x":{"diagram":"digraph {\n  graph [layout = dot, rankdir = TB]\n  \n  node [shape = rectangle]     \n  rec0 [label = \"CONDITIONAL PROCESS ANALYSIS\"]\n  rec1 [label = \"A) Conditional Direct and Indirect Effects\"]\n  rec2 [label = \"B) Conditional Indirect Effect Model\"]\n  rec3 [label = \"C) Conditional Direct and Indirect Effect Model\"]\n  rec4 [label = \"D) Conditional Model with Multicategorical Antecedent\"]\n  rec5 [label = \"E) Check the Assumptions\"]\n\n  # edge definitions with the node IDs\n  rec0 -> rec1 -> rec2 -> rec3 -> rec4 -> rec5;\n  }","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="the-concept-of-conditional-process" class="level1">
<h1>The concept of conditional process</h1>
<p>Conditional processes analysis is a combination of mediation and moderation analysis.</p>
<ul>
<li>Mediation analysis is intended to understand the mechanisms through which <span class="math inline">\(X\)</span> impacts <span class="math inline">\(Y\)</span>. It is characterized by direct and indirect effects.</li>
<li>Moderation analysis consists in understanding the conditions which alter the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. It is characterized by conditional effect.</li>
<li>Conditional process analysis is used to understand the <em>conditions that affect the mechanisms</em> by which a variable transmits its its effect on another. It is characterized by conditional direct and indirect effect.</li>
</ul>
<p>When multicategorical variables are involved in the process, the effects are called relative conditional direct and indirect effects.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/schema_models.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>It is also called “moderated mediation”. Due to the complexity of human and social processes, conditional process models may generally be more appropriate than mediation and moderation models only.</p>
<section id="conceptual-diagram" class="level2">
<h2 class="anchored" data-anchor-id="conceptual-diagram">Conceptual diagram</h2>
<p>The diagram of the conditional process is also a combination of mediation and moderation diagrams. Basically, starting from a mediation model, a conditional process model is created when one or more relations are conditioned by a moderator variable.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-diagrams.png" class="img-fluid" width="588"></p>
</div>
</div>
</section>
<section id="types-of-conditional-process" class="level2">
<h2 class="anchored" data-anchor-id="types-of-conditional-process">Types of conditional process</h2>
<p>There are three principal cases of conditional processes:</p>
<ol type="1">
<li>Moderation only applies to the direct effect of a mediation model. In this case we have a <em>conditional direct effect</em>.</li>
<li>Moderation only applies to the indirect effect. In this case we have a <em>conditional indirect effect</em>.</li>
<li>Moderation applies to both the direct and indirect effect. In this case we have both <em>conditional direct and indirect effects</em>.</li>
</ol>
<p>Given that conditional direct and indirect effects are a combination of mediation and moderation effects, it may be helpful to briefly summarize them in order to better understand the former.</p>
</section>
<section id="recap-of-direct-and-indirect-effects" class="level2">
<h2 class="anchored" data-anchor-id="recap-of-direct-and-indirect-effects">Recap of direct and indirect effects</h2>
<p>A mediation model divides the total effect (<span class="math inline">\(c\)</span>) of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> into a direct effect (<span class="math inline">\(c'\)</span>) and indirect effect (<span class="math inline">\(a*b\)</span>), such that <span class="math inline">\(c = c' + a*b\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/mediation_1_diagram_1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>In greater detail:</p>
<ul>
<li>The direct effect (<span class="math inline">\(c'\)</span>) quantifies the change in the estimate of <span class="math inline">\(Y\)</span> for a one-unit change in <span class="math inline">\(X\)</span>, partialing out the effect of other variables in the model (i.e., the mediator <span class="math inline">\(M\)</span>, and other possible covariates).</li>
<li>The indirect effect quantifies the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> through <span class="math inline">\(M\)</span>, independent of the direct effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> and possible covariates. It is denoted as <span class="math inline">\(ab\)</span> and results from the product of the coefficients <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> (indirect effect = <span class="math inline">\(a * b\)</span>).</li>
<li>The total effect is the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> in a model that does not include <span class="math inline">\(M\)</span>. It is denoted as <span class="math inline">\(c\)</span>. It is the sum of the direct and indirect effect: <span class="math inline">\(c = c' + ab\)</span>.</li>
</ul>
</section>
<section id="recap-of-conditional-effects" class="level2">
<h2 class="anchored" data-anchor-id="recap-of-conditional-effects">Recap of conditional effects</h2>
<p>In a moderation model, the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is conditional on the values of a moderator <span class="math inline">\(W\)</span>. This means that the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is expressed as a <em>function</em>, which we called <em>theta</em> (<span class="math inline">\(\theta\)</span>).</p>
<p>Given a simple moderation model, the conditional effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is expressed as the regression coefficient of <span class="math inline">\(X\)</span> plus the coefficient of the interaction term <span class="math inline">\(XW\)</span>, multiplied by the value of <span class="math inline">\(W\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/cond_effect.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>In more detail:</p>
<p>In moderation models, the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is no more expressed by a single coefficient, but by a function. A function is just a mathematical “mechanism” that transforms inputs into outputs (for instance, multiplication is a function whose inputs are two numbers, the multiplicand and the multiplier, which are converted into a number called the “product”).</p>
<p>The conditional effect is a function whose output quantifies how the effect of the independent variable <span class="math inline">\(X\)</span> on the dependent variable <span class="math inline">\(Y\)</span> changes as the moderator increases by one unit. We have denoted this function with the Greek letter “theta”(<span class="math inline">\(\theta_{X \to Y}\)</span>).</p>
<p>Perhaps the best way to understand the conditional effect is to look at the regression equation.</p>
<p>Consider a regression model with an independent <span class="math inline">\(X\)</span> variable and a dependent <span class="math inline">\(Y\)</span> variable that also includes a <span class="math inline">\(W\)</span> moderator. The relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is moderated. This regression model includes the coefficient of <span class="math inline">\(X\)</span>, that of <span class="math inline">\(W\)</span> and the one of the interaction between <span class="math inline">\(X\)</span> and <span class="math inline">\(W\)</span> (<span class="math inline">\(XW\)</span>).</p>
<p><span class="math display">\[\hat Y = b_1X + b_2W + b_3XW\]</span></p>
<p>In a regression model without moderation there is no interaction between <span class="math inline">\(X\)</span> and <span class="math inline">\(W\)</span>. The effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is expressed by a single coefficient, that of <span class="math inline">\(X\)</span> (<span class="math inline">\(b_1X\)</span>). Instead, in a moderation model, the effect of <span class="math inline">\(X\)</span> is expressed by both <span class="math inline">\(b_1X\)</span> and the interaction term <span class="math inline">\(b_3XW\)</span>. To find the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> we have to collect the terms involving <span class="math inline">\(X\)</span> and then factoring out <span class="math inline">\(X\)</span>.</p>
<p><span class="math display">\[\hat Y = (b_1 + b_3W)X + b_2W\]</span></p>
<p>We can see that the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is no more a number, as in a regression model without interaction, but a function: <span class="math inline">\((b_1 + b_3W)\)</span>.</p>
<p><span class="math display">\[\theta_{X \to Y} = b_1 + b_3W\]</span></p>
<p>The output of the function depends on the value of <span class="math inline">\(W\)</span>. For instance, consider <span class="math inline">\(b_1\)</span> the coefficient of <span class="math inline">\(X\)</span> = <code>negemot</code> = 0.120, and <span class="math inline">\(b_3\)</span> the coefficient of the interaction term <span class="math inline">\(W\)</span> = 0.006. By plugging these values into the function of the conditional effect, we can see that the output varies depending on the values of <span class="math inline">\(W\)</span> (this procedure is also known as the pick-a-point method, which is used to probe the interaction). The output of the function is the conditional effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[\theta_{X \to Y} = 0.120 + 0.006W \]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> <span class="cf">function</span>(W){<span class="fl">0.120</span> <span class="sc">+</span> <span class="fl">0.006</span><span class="sc">*</span>W}</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">50</span>,<span class="dv">70</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="st">"Age"</span> <span class="ot">=</span> W, <span class="st">"Conditional_Effect"</span> <span class="ot">=</span> <span class="fu">theta</span>(W))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Age Conditional_Effect
1  30               0.30
2  50               0.42
3  70               0.54</code></pre>
</div>
</div>
</section>
</section>
<section id="conditional-indirectdirect-effect" class="level1">
<h1>Conditional indirect/direct effect</h1>
<p>In the conditional process analysis, the conditional effect is used to determine direct and/or indirect effects.</p>
<p>Once you are familiar with mediation and moderation models, the intuition behind conditional process models is straightforward. When one of the paths of a mediation model is moderated, the corresponding direct or indirect effect becomes a conditional effect (<span class="math inline">\(\theta\)</span>). This conditional effect is then used in the mediation model to determine the corresponding direct or indirect effect.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/cond_ind_diag.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>For instance, if the <span class="math inline">\(a\)</span> path is moderated, the indirect effect <span class="math inline">\(a*b\)</span> is computed as <span class="math inline">\(\theta * b\)</span>. Likewise, if the direct effect <span class="math inline">\(c'\)</span> is moderate, it will be expressed by means of a conditional effect function.</p>
<p>As a result, direct and indirect effects, now conditional direct and indirect effects, are analyzed using the statistical instruments of moderation analysis, such as the <em>pick-a-point</em> approach and the <em>Johnson-Neyman</em> significance regions.</p>
<p>So not only are the diagrams and effects of conditional process models a mixture of mediation and moderation models. The output of a conditional process model fitted with PROCESS, and its interpretation, is also a blend of the results of the mediation and moderation models.</p>
<p>In the following sections, we discuss the conditional direct effect model, the conditional indirect effect model, and the conditional direct and indirect effect model.</p>
<section id="conditional-direct-effect" class="level2">
<h2 class="anchored" data-anchor-id="conditional-direct-effect">Conditional direct effect</h2>
<p>The conceptual and statistical diagram for a model with only a conditional direct effect is the following.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex1-conditional-process.png" class="img-fluid" width="711"></p>
</div>
</div>
<p>The model comprises four variables, <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, <span class="math inline">\(M\)</span>, and the moderator <span class="math inline">\(W\)</span>. Like any simple mediation model, it consists of two equations, one for each outcome variable (<span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span>).</p>
<p><span class="math display">\[M = i_M + aX + e_M\]</span> <span class="math display">\[Y = i_Y + c'_1X +  c'_2W +  c'_3XW + bM + e_Y\]</span></p>
<p>The outcome of the first equation is <span class="math inline">\(M\)</span>, which is predicted by <span class="math inline">\(X\)</span>. The outcome of the second equation is <span class="math inline">\(Y\)</span>, which is predicted by both <span class="math inline">\(X\)</span> and <span class="math inline">\(M\)</span>. Additionally, the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is moderated by <span class="math inline">\(W\)</span>, so the second model also includes the variable <span class="math inline">\(W\)</span> and the interaction term <span class="math inline">\(XW\)</span>.</p>
<p>For clarity, we can ignore the intercept <span class="math inline">\(i_M\)</span> and the error term <span class="math inline">\(e_Y\)</span>.</p>
<p>Only the second equation comprises a conditional effect, because only that equation has a moderator. More precisely, moderator <span class="math inline">\(W\)</span> moderates the direct effect between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. This is therefore a conditional direct effect, which is now expressed by a function instead of the single coefficient <span class="math inline">\(c'\)</span>. We can find the effect by grouping terms in the equation involving <span class="math inline">\(X\)</span> and then factoring out <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[\hat Y = c'_1X +  c'_2W +  c'_3XW + bM\]</span> <span class="math display">\[\hat Y = (c'_1 + c'_3W)X +  c'_2W + + bM\]</span></p>
<p>The conditional direct effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is represented by the function between round brackets:</p>
<p><span class="math display">\[\theta_{X \to Y} = c'_1 + c'_3W\]</span></p>
<p>It quantifies how the effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> changes independent of the mediator <span class="math inline">\(M\)</span> (which is kept constant) for a one-unit change of <span class="math inline">\(W\)</span>.</p>
</section>
<section id="conditional-indirect-effect" class="level2">
<h2 class="anchored" data-anchor-id="conditional-indirect-effect">Conditional indirect effect</h2>
<p>This is the conceptual and statistical diagram for a model with only a conditional indirect effect:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex2-conditional-process.png" class="img-fluid" width="698"></p>
</div>
</div>
<p>The model comprises four variables, <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, <span class="math inline">\(M\)</span>, and the moderator <span class="math inline">\(W\)</span>. Like a simple mediation model, it consists of two equations, one for each outcome variable (<span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span>).</p>
<p>The outcome of the first equation is <span class="math inline">\(M\)</span>, which is predicted by <span class="math inline">\(X\)</span>. The outcome of the second equation is <span class="math inline">\(Y\)</span>, which is predicted by both <span class="math inline">\(X\)</span> and <span class="math inline">\(M\)</span>. Additionally, the relationship between <span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span> is moderated by <span class="math inline">\(W\)</span>, so the second model also includes the variable <span class="math inline">\(W\)</span> and the interaction term <span class="math inline">\(MW\)</span>.</p>
<p><span class="math display">\[M = i_M + aX + e_M\]</span> <span class="math display">\[Y = i_Y + c'_1X + b_1M + b_2W + b_3MW + e_Y\]</span></p>
<p>For clarity, we can ignore the intercept <span class="math inline">\(i_M\)</span> and the error term <span class="math inline">\(e_Y\)</span>.</p>
<p>Only the second equation comprises a moderating effect and, consequently, a conditional effect. Moderator W moderates the relation between <span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span>, so we can find this effect by grouping the M terms together.</p>
<p><span class="math display">\[\hat Y = c'_1X + b_1M + b_2W + b_3MW\]</span> <span class="math display">\[\hat Y = c'_1X + (b_1 + b_3W)M + b_2W\]</span></p>
<p>The conditional effect is represented by the function within parentheses:</p>
<p><span class="math display">\[\theta_{M \to Y} = b_1 + b_3W\]</span></p>
<p>This conditional indirect effect quantifies how differences in <span class="math inline">\(X\)</span> map onto differences in <span class="math inline">\(Y\)</span> indirectly through M depending on the value of <span class="math inline">\(W\)</span>.</p>
<p>The moderated relation contributes to define the indirect effect. In a simple mediation model, the indirect effect is defined as the product between the coefficients <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, <span class="math inline">\(ab = a * b\)</span>. In this conditional process model, <span class="math inline">\(b\)</span> is no more a single coefficient but a function, i.e., the function defining the conditional effect. It follows that the conditional indirect effect is the product between <span class="math inline">\(a\)</span> and the conditional effect <span class="math inline">\(\theta_{M \to Y} = b_1 + b_3W\)</span>, and its value is conditional on W:</p>
<p><span class="math display">\[a(b_1 + b_3W) = ab_1 + a_b3W\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex2-conditional-process.png" class="img-fluid" width="698"></p>
</div>
</div>
<p>The following is the conceptual and statistical diagram for a model with a conditional direct and indirect effect:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex3-conditional-process.png" class="img-fluid" width="692"></p>
</div>
</div>
<p>The model comprises five variables, <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, <span class="math inline">\(M\)</span>, and the moderators <span class="math inline">\(W\)</span> and <span class="math inline">\(Z\)</span>. Like a simple mediation model, it consists of two equations, one for each outcome variable (<span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span>).</p>
<p>The outcome of the first equation is <span class="math inline">\(M\)</span>, which is predicted by <span class="math inline">\(X\)</span>. Additionally, <span class="math inline">\(W\)</span> moderates the relation between <span class="math inline">\(X\)</span> and <span class="math inline">\(M\)</span>, so the model includes the coefficient for <span class="math inline">\(W\)</span> and the interaction between <span class="math inline">\(X\)</span> and <span class="math inline">\(W\)</span>.</p>
<p><span class="math display">\[M = i_M + a_1X + a_2W + a_3XW + e_M\]</span></p>
<p>The outcome of the second equation is <span class="math inline">\(Y\)</span>, which is predicted by both <span class="math inline">\(X\)</span> and <span class="math inline">\(M\)</span>. Additionally, the relationship between <span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span> is moderated by <span class="math inline">\(Z\)</span>, and so it is the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. SO the model includes the coefficient for <span class="math inline">\(Z\)</span>, and those for the interaction between <span class="math inline">\(X\)</span> and <span class="math inline">\(Z\)</span> (<span class="math inline">\(XZ\)</span>), and <span class="math inline">\(M\)</span> and <span class="math inline">\(Z\)</span> (<span class="math inline">\(MZ\)</span>):</p>
<p><span class="math display">\[Y = i_Y + c'_1X + c'_2Z + c'_3XZ + b_1M + b_2MZ + e_Y\]</span></p>
<p>For clarity, we can ignore intercepts and error terms.</p>
<p>As we have interactions in both equations, they both include conditional effects. More precisely, the first equation includes a conditional indirect effect, and the second a conditional direct and indirect effect.</p>
<p>Starting from the first equation, we can find the conditional indirect effects by grouping <span class="math inline">\(X\)</span> terms and factoring out <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[\hat M = a_1X + a_2W + a_3XW\]</span> <span class="math display">\[\hat M = (a_1 + a_3W)X + a_2W\]</span> <span class="math display">\[\theta_{X \to M} = a_1 + a_3W\]</span></p>
<p>Considering the second equation, we can find the conditional indirect effects by grouping the <span class="math inline">\(X\)</span> terms and factoring out <span class="math inline">\(X\)</span>, and the conditional indirect effects by grouping the <span class="math inline">\(M\)</span> terms and factoring out <span class="math inline">\(M\)</span>:</p>
<p><span class="math display">\[Y = c'_1X + c'_2Z + c'_3XZ + b_1M + b_2MZ\]</span> <span class="math display">\[Y = (c'_1 + c'_3Z)X + (b_1 + b_2Z)M +  + c'_2Z\]</span></p>
<p>The two conditional effects are within parentheses. The conditional <em>direct</em> effect and and the conditional <em>indirect</em> effect is the former (<span class="math inline">\(\theta_{X \to Y}\)</span>) and the latter (<span class="math inline">\(\theta_{M \to Y}\)</span>), respectively:</p>
<p><span class="math display">\[\theta_{X \to Y} = c'_1 + c'_3Z\]</span> <span class="math display">\[\theta_{M \to Y} = b_1 + b_2Z\]</span></p>
<p>As previously explained, given a mediation model <span class="math inline">\(X \to M \to Y\)</span> with coefficient <span class="math inline">\(a\)</span> (path from <span class="math inline">\(X\)</span> to <span class="math inline">\(M\)</span>) and <span class="math inline">\(b\)</span> (path from <span class="math inline">\(M\)</span> to <span class="math inline">\(Y\)</span>), the indirect effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is the product between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> <span class="math inline">\(ab = a * b\)</span>. The conditional indirect effect is the product of the same paths where one or both are dependent on a moderator and are therefore represented by conditional effects. In our case, both the paths are conditioned on a moderator (respectively <span class="math inline">\(W\)</span> and <span class="math inline">\(Z\)</span>), so the indirect effect is the product of these conditional effects:</p>
<p><span class="math display">\[\theta_{X \to M} * \theta_{M \to Y}\]</span> <span class="math display">\[(a_1 + a_3W) * (b_1 + b_2Z)\]</span> <span class="math display">\[a_1b_1 + a_1b_2Z + a_3b_1W + a_3b_2WZ\]</span></p>
</section>
</section>
<section id="moderation-of-a-specific-indirect-effect-in-a-parallel-multiple-mediator-model" class="level1">
<h1>Moderation of a specific indirect effect in a parallel multiple mediator model</h1>
<p>There are also more complicated models, such as parallel multiple mediator models involving one moderator that moderates one of the mediated effects. The model depicted below, for instance, includes three outcomes and three equations. The book provides further details.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex4-conditional-process.png" class="img-fluid" width="688"></p>
</div>
</div>
<p>We will now examine how to fit and interpret conditional indirect effect models, conditional indirect and direct effect models, and conditional models with multicategorical variables.</p>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>In the following example we’ll use the dataset <span class="math inline">\(TEAMS\)</span> to fit a conditional indirect effect model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>teams <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(<span class="st">"data/teams.sav"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data comes from a study on work teams. The goal was to examine the mechanism by which the dysfunctional behavior of members of a work team (<code>dysfunc</code> = <span class="math inline">\(X\)</span>) can negatively affect the ability of a work team to perform well (<code>perform</code> = <span class="math inline">\(Y\)</span>). The researchers proposed a mediation model in which dysfunctional behavior (<span class="math inline">\(X\)</span>) leads to a work environment filled with negative emotions (<code>negtone</code> = <span class="math inline">\(M\)</span>) that supervisors and other employees confront and attempt to manage, which then distracts from work and interferes with task performance (<span class="math inline">\(Y\)</span>).</p>
<p>However, according to the authors’ model, when team members are able to regulate their display of negative emotions (<code>negexp</code> = <span class="math inline">\(W\)</span>), essentially hiding how they are feeling from others, this allows the team to stay focused on the task at hand rather than having to shift focus toward managing the negative tone of the work environment and the feelings of others.</p>
<p>That is, the effect of negative affective tone of the work environment on team performance is hypothesized in their model as contingent on the ability of the team members to hide their feelings from the team, with a stronger negative effect of negative affective tone on performance in teams that express their negativity rather than conceal it.</p>
</section>
</section>
<section id="conditional-indirect-effect-model-with-process" class="level1">
<h1>Conditional indirect effect model with process</h1>
<p>The describe model can be fitted in <code>process</code> by using <code>model = 14</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"PROCESS_R/process.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
 
PROCESS is now ready for use.
Copyright 2021 by Andrew F. Hayes ALL RIGHTS RESERVED
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"perform"</span>, <span class="at">x =</span> <span class="st">"dysfunc"</span>, <span class="at">m =</span> <span class="st">"negtone"</span>, <span class="at">w =</span> <span class="st">"negexp"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">14</span>, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">jn =</span> <span class="dv">1</span>, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot =</span> <span class="dv">1</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.2</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">seed=</span><span class="dv">42517</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">boot =</span> <span class="dv">5000</span>, <span class="co"># number of bootstraps</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">progress =</span> <span class="dv">0</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> teams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
               
Model : 14     
    Y : perform
    X : dysfunc
    M : negtone
    W : negexp 

Sample size: 60

Custom seed: 42517


*********************************************************************** 
Outcome Variable: negtone

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.44       0.19       0.23      13.80       1.00      58.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       0.03       0.06       0.42       0.68      -0.10       0.15
dysfunc        0.62       0.17       3.71       0.00       0.29       0.95

*********************************************************************** 
Outcome Variable: perform

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.56       0.31       0.20       6.24       4.00      55.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant      -0.01       0.06      -0.20       0.84      -0.13       0.11
dysfunc        0.37       0.18       2.06       0.04       0.01       0.72
negtone       -0.44       0.13      -3.34       0.00      -0.70      -0.17
negexp        -0.02       0.12      -0.16       0.87      -0.25       0.22
Int_1         -0.52       0.24      -2.15       0.04      -1.00      -0.03

Product terms key:
Int_1  :  negtone  x  negexp      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
M*W       0.06       4.60       1.00      55.00       0.04
----------
Focal predictor: negtone (M)
      Moderator: negexp (W)

Conditional effects of the focal predictor at values of the moderator(s):
      negexp     effect         se          t          p       LLCI       ULCI
       -0.53      -0.16       0.21      -0.77       0.44      -0.58       0.26
       -0.06      -0.40       0.14      -2.98       0.00      -0.68      -0.13
        0.60      -0.75       0.16      -4.59       0.00      -1.07      -0.42

Moderator value(s) defining Johnson-Neyman significance region(s):
       Value    % below    % above
       -0.23      35.00      65.00

Conditional effect of focal predictor at values of the moderator:
      negexp     effect         se          t          p       LLCI       ULCI
       -1.16       0.16       0.34       0.48       0.63      -0.52       0.85
       -1.06       0.11       0.32       0.34       0.73      -0.53       0.75
       -0.95       0.06       0.30       0.19       0.85      -0.54       0.65
       -0.85       0.00       0.27       0.01       0.99      -0.55       0.55
       -0.74      -0.05       0.25      -0.21       0.84      -0.56       0.45
       -0.64      -0.11       0.23      -0.46       0.65      -0.57       0.35
       -0.53      -0.16       0.21      -0.77       0.45      -0.58       0.26
       -0.43      -0.21       0.19      -1.13       0.26      -0.59       0.17
       -0.32      -0.27       0.17      -1.57       0.12      -0.61       0.08
       -0.23      -0.31       0.16      -2.00       0.05      -0.63      -0.00
       -0.22      -0.32       0.16      -2.08       0.04      -0.63      -0.01
       -0.11      -0.38       0.14      -2.66       0.01      -0.66      -0.09
       -0.01      -0.43       0.13      -3.28       0.00      -0.69      -0.17
        0.09      -0.48       0.13      -3.86       0.00      -0.74      -0.23
        0.20      -0.54       0.12      -4.32       0.00      -0.79      -0.29
        0.30      -0.59       0.13      -4.60       0.00      -0.85      -0.33
        0.41      -0.65       0.14      -4.71       0.00      -0.92      -0.37
        0.51      -0.70       0.15      -4.68       0.00      -1.00      -0.40
        0.62      -0.75       0.17      -4.57       0.00      -1.09      -0.42
        0.72      -0.81       0.18      -4.42       0.00      -1.17      -0.44
        0.83      -0.86       0.20      -4.27       0.00      -1.27      -0.46
        0.93      -0.92       0.22      -4.12       0.00      -1.36      -0.47

Data for visualizing the conditional effect of the focal predictor:
     negtone     negexp    perform
       -0.45      -0.53       0.08
       -0.04      -0.53       0.02
        0.52      -0.53      -0.07
       -0.45      -0.06       0.18
       -0.04      -0.06       0.02
        0.52      -0.06      -0.21
       -0.45       0.60       0.32
       -0.04       0.60       0.02
        0.52       0.60      -0.40

*********************************************************************** 
Bootstrapping in progress. Please wait.

**************** DIRECT AND INDIRECT EFFECTS OF X ON Y ****************

Direct effect of X on Y:
      effect         se          t          p       LLCI       ULCI
        0.37       0.18       2.06       0.04       0.01       0.72

Conditional indirect effects of X on Y:

INDIRECT EFFECT:

dysfunc    -&gt;    negtone    -&gt;    perform

      negexp     Effect     BootSE   BootLLCI   BootULCI
       -0.53      -0.10       0.15      -0.37       0.24
       -0.06      -0.25       0.12      -0.49      -0.04
        0.60      -0.46       0.17      -0.81      -0.15

     Index of moderated mediation:
            Index     BootSE   BootLLCI   BootULCI
negexp      -0.32       0.19      -0.76      -0.04

---

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

Number of bootstraps for percentile bootstrap confidence intervals: 5000

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>The output includes:</p>
<ul>
<li><p>Summary statistics of the model (model summary);</p></li>
<li><p>Two regression tables with the coefficients for the first model (outcome: <code>negtone</code>) and the second (outcome: <code>perform</code>);</p></li>
<li><p>Tables resulting from the pick-a-point and the Johnson-Neyman technique;</p></li>
<li><p>Data to visualize the moderation effect;</p></li>
<li><p>Tables on the direct and indirect effect.</p></li>
</ul>
<section id="conditional-indirect-effect-1" class="level2">
<h2 class="anchored" data-anchor-id="conditional-indirect-effect-1">Conditional indirect effect</h2>
<p>Looking at the two regression tables, the model can be written as:</p>
<p><span class="math display">\[M = i_M + aX\]</span> <span class="math display">\[Y = i_Y + c'X + b_1M + b_2W + b_3MW + e_Y\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1b.png" class="img-fluid" width="516"></p>
</div>
</div>
<p>In a simple mediation model, the conditional indirect effect is the product between <span class="math inline">\(a\)</span> (the path from <span class="math inline">\(X\)</span> to <span class="math inline">\(M\)</span>) and <span class="math inline">\(b\)</span> (the path from <span class="math inline">\(M\)</span> to <span class="math inline">\(Y\)</span>). Here <span class="math inline">\(a\)</span> corresponds to <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> to <span class="math inline">\(b_1\)</span>.</p>
<p>Whereas the path <span class="math inline">\(X \to M\)</span> is not moderated and therefore <span class="math inline">\(a\)</span> is a simple coefficient, the path <span class="math inline">\(M \to Y\)</span> is moderated by W and therefore <span class="math inline">\(b_1\)</span> is a conditional effect expressed through a function, we can denote as <span class="math inline">\(\theta_{M \to Y}\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1.png" class="img-fluid" width="681"></p>
</div>
</div>
<p>We can find the conditional effect by grouping the <span class="math inline">\(M\)</span> terms and factoring out <span class="math inline">\(M\)</span> (we ignore the intercept and error term).</p>
<p><span class="math display">\[\hat Y = c'X + b_1M + b_2W + b_3MW\]</span> <span class="math display">\[\hat Y = c'X + (b_1 + b_3W)M + b_2W\]</span> <span class="math display">\[\theta_{M \to Y} = b_1 + b_3W\]</span></p>
<section id="conditional-effect" class="level3">
<h3 class="anchored" data-anchor-id="conditional-effect">Conditional effect</h3>
<p>The conditional effect <span class="math inline">\(\theta_{M \to Y} = b_1 + b_3W\)</span> represents the moderation effect. As in a simple moderation model, it is analyzed in the second part of the output. Here you will find the table Conditional effects of the focal predictor at values of the moderator(s) (resulting from the pick-a-point approach), and the table Johnson-Neyman significance regions.</p>
<p>Consider the table Conditional effects of the focal predictor at values of the moderator(s). The function just identified for the conditional effect can be used to test the effect of <span class="math inline">\(M\)</span> on <span class="math inline">\(Y\)</span> at different levels of the moderator <span class="math inline">\(W\)</span>. For example, at relatively low (-0.53), moderate (-0.06), and relatively high (0.60) level of the moderator, we obtain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cond_ind_effect <span class="ot">&lt;-</span> <span class="cf">function</span>(W) { <span class="sc">-</span><span class="fl">0.44</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.52</span><span class="sc">*</span>W }</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>moderator_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.53</span>, <span class="sc">-</span><span class="fl">0.06</span>, <span class="fl">0.60</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(moderator_values, cond_ind_effect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1644 -0.4088 -0.7520</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1d.png" class="img-fluid" width="487"></p>
</div>
</div>
</section>
<section id="conditional-indirect-effect-2" class="level3">
<h3 class="anchored" data-anchor-id="conditional-indirect-effect-2">Conditional indirect effect</h3>
<p>We can now find the conditional indirect effect by multiplying the conditional effect <span class="math inline">\(\theta_{M \to Y}\)</span> by <span class="math inline">\(a\)</span>. Here <span class="math inline">\(a\)</span> is the coefficient of <code>dysfunc</code> (first regression table, <code>dysfunc</code> = 0.62), <span class="math inline">\(b_1\)</span> is the coefficient of <code>negtone</code> (<span class="math inline">\(M \to Y\)</span>) (second regression table <code>negtone</code> = -0.44), and <span class="math inline">\(b_3\)</span> is the coefficient of the interaction term (second regression table, Int_1 = -0.52).</p>
<p><span class="math display">\[a\theta_{M \to Y}\]</span> <span class="math display">\[a(b_1 + b_3W)\]</span> <span class="math display">\[0.62(-0.44 + -0.52W)\]</span></p>
<p>The conditional indirect effect is analyzed through a pick-a-point approach: various values of the moderator W are plugged into the function of the conditional indirect effect (<span class="math inline">\(0.62(-0.44 + -0.52W)\)</span>). A significance test is subsequently conducted. The results are presented in the last section of the output. The table <em>Conditional indirect effects of</em> <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> shows the changes in the <span class="math inline">\(Y\)</span> estimates for a one-unit change in <span class="math inline">\(X\)</span> through the mediator <span class="math inline">\(M\)</span> at different levels of the moderator (Using Hayes’ own words: <em>“the conditional indirect effect of X on Y through M conditioned on W quantifies the amount by which two cases with a given value of W that differ by one unit on X are estimated to differ on Y indirectly through X’s effect on M, which in turn influences Y.”</em>).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1d.png" class="img-fluid" width="487"></p>
</div>
</div>
<p>In practice, the table can be read as follows: <em>“at relatively low levels of emotional expressiveness (the moderator) there is no evidence of an effect of dysfunctional behavior on performance through negative emotional tone (-0.53, 95% CI [-0.37, 0.24]). Instead, at moderate (-0.06, 95% CI [-0.49, 0.04]) to relatively high (0.60, 95% CI [-0.81, -0.15]) levels of emotional expressivity, the effect is statistically significant, with higher levels of emotional expressiveness leading to worse team performance</em>.</p>
<p>The Index of moderated mediation is displayed right below the pick-a-point table. It provides the results of a more general significance test of the relationship between the moderator and the indirect effect. When zero is not within the range of the confidence interval, it can be concluded that the indirect effect is associated with the moderator. Had the confidence interval included zero, we could not definitively claim that the indirect effect was related to the moderator.</p>
<p>In this case the “index” is negative, which leads to the conclusion that the indirect effect is <em>negatively</em> related to the moderator. That is, the mediation of the effect of dysfunctional team behavior on performance through negative affective tone of the work climate is moderated by the expressiveness of the team.</p>
<p>The Index of moderated mediation is displayed if <span class="math inline">\(W\)</span> is specified as a moderator of only one of the paths that define the indirect effect. Otherwise, the indirect effect will be a nonlinear function of <span class="math inline">\(W\)</span>. In that case, <code>process</code> will not produce this index.</p>
<p>In the section of the output there is also the direct effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>. In this case it is not affected by the moderator and can be interpreted as in a simple mediation model.</p>
</section>
</section>
</section>
<section id="visualize-the-conditional-effect" class="level1">
<h1>Visualize the conditional effect</h1>
<p>Visualization data are provided for the moderation effect, as in a simple moderation model, and can be plotted as learned in the previous lectures.</p>
<p>Instead, <code>process</code> does not provide data for visualization of the indirect or direct conditional effect. If you want to create this picture, <em>you need to do it yourself</em>. That takes a little more familiarity with R. However, there is no need to create the chart because the relevant information is provided in the tables.</p>
<p>The dataset that allows visualization of the data must contain two columns. The former should contain the values of the direct effect and the latter the values for the indirect effect at the moderator levels. Data should be generated with the function of the direct and/or indirect conditional effect, if the direct and/or indirect effect is affected by a moderator. The function has to be identified in the equation of the model as described above.</p>
<p>The plot consists of the following structure: the effects are on the vertical axis and the values of the moderator on the horizontal axis. Additionally, different types of lines should distinguish the direct and indirect effects.</p>
<p>We already found the function (conditional effect) needed to calculate the indirect effect <span class="math inline">\(a(b_1 + b_3W)\)</span>, resulting in the function <span class="math inline">\(-0.2728 -0.3224W\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># INDIRECT EFFECT DATA - - - - - - - - - - - - - - - - - - - </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># create a function to calculate the indirect effect </span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (based on the model equation)</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ind_effect <span class="ot">&lt;-</span> <span class="cf">function</span>(W) {<span class="fl">0.62</span><span class="sc">*</span>(<span class="sc">-</span><span class="fl">0.44</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.52</span><span class="sc">*</span>W)}</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># choose the 16th, 50th, and 86th percentile of the moderator</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>w1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(teams<span class="sc">$</span>negexp, <span class="fl">0.16</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>w2 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(teams<span class="sc">$</span>negexp, <span class="fl">0.50</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>w3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(teams<span class="sc">$</span>negexp, <span class="fl">0.86</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># apply the function to different levels of W</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>indirect_effect <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(w1 , w2, w3), ind_effect))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># DIRECT EFFECT DATA - - - - - - - - - - - - - - - - - - - </span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># in this case the direct effect is not moderated and is always 0.37</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>direct_effect <span class="ot">&lt;-</span>  <span class="fu">rep</span>(<span class="fl">0.37</span>, <span class="dv">3</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># MERGE DIRECT AND DIRECT EFFECT IN A VECTOR OF LENGTH 6</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(direct_effect, indirect_effect)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># CREATE A VECTOR OF LENGHT 6 TO DISTINGUISH DIRECT AND INDIRECT EFFECT DATA - - - </span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>type <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>) </span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># CREATE A VECTOR OF LENGHT 6 WITH THE VALUES OF THE MDOERATOR - - - - - - - - - - </span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(w1, w2, w3, w1, w2, w3)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> y, <span class="co"># the effect on the vertical axis</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>     <span class="at">x =</span> w, <span class="co"># values of the moderator on the horizontal axis</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">15</span>,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"white"</span>,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Nonverbal negative expressivity"</span>,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Effect of dysfunctional team behavior on performance"</span>,</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.7</span>),</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.5</span>))</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>legend.txt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Direct effect"</span>, <span class="st">"Indirect effect"</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomleft"</span>, <span class="at">legend =</span> legend.txt, </span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">3</span>))</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w[type<span class="sc">==</span><span class="dv">0</span>], y[type<span class="sc">==</span><span class="dv">0</span>], <span class="at">lwd =</span> <span class="dv">4</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(w[type<span class="sc">==</span><span class="dv">1</span>], y[type<span class="sc">==</span><span class="dv">1</span>], <span class="at">lwd =</span> <span class="dv">4</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="conditional_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conditional-effect-1" class="level1">
<h1>Conditional effect</h1>
<p>We have already demonstrated that the <em>conditional effect</em> is a component of the <em>conditional indirect effect</em>. On its own, it the <em>conditional effect</em> is composed by two coefficients: that of <span class="math inline">\(X\)</span> and the interaction term <span class="math inline">\(X*W\)</span> or <code>Int_1</code>. <code>Int_1</code> quantifies the degree to which the conditional effect of <span class="math inline">\(M\)</span> on <span class="math inline">\(Y\)</span> changes when <span class="math inline">\(W\)</span> changes by one unit. As <span class="math inline">\(W\)</span> changes by 1 unit, the conditional effect of <span class="math inline">\(M\)</span> on <span class="math inline">\(Y\)</span> changes by the “<code>Int_1</code> coefficient”, or -0.52 units (p = 0.04).</p>
<p><span class="math display">\[\hat Y = c'X + b_1M + b_2W + b_3MW\]</span> <span class="math display">\[\hat Y = c'X + (b_1 + b_3W)M + b_2W\]</span> <span class="math display">\[\theta_{M \to Y} = b_1 + b_3W\]</span> <span class="math display">\[\theta_{M \to Y} = -0.44 -0.52W\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1b.png" class="img-fluid" width="516"></p>
</div>
</div>
<p>As in a simple moderation model, the second section of the result presents the tables devoted to the analysis of the moderating effect.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1c.png" class="img-fluid" width="508"></p>
</div>
</div>
<p>The <em>conditional effect</em> function is used for probing the interaction at different levels of <span class="math inline">\(W\)</span>. We observe that the interaction is not significant for low levels of the moderator (that is, when people show weak levels of emotional expression). As the moderator is continuous, it is also possible to see the Johnson-Neyman table defining the significant regions. It shows that the moderator begins to exert a significant effect at values greater than -0.23.</p>
<p>Data to visualize the moderation effect is provided. The interaction graph clearly indicates what is already indicated in the table Conditional effects of the focal predictor at values of the moderator(s). The higher the expressiveness, the greater the negative impact the negative tone has on the team’s performance. Or vice-versa, the lower the expressiveness, the lower the impact of negative emotions on team performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.45</span>,   <span class="sc">-</span><span class="fl">0.04</span>,  <span class="fl">0.52</span>,   <span class="sc">-</span><span class="fl">0.45</span>,  <span class="sc">-</span><span class="fl">0.04</span>,  <span class="fl">0.52</span>,   <span class="sc">-</span><span class="fl">0.45</span>,  <span class="sc">-</span><span class="fl">0.04</span>,  <span class="fl">0.52</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.53</span>, <span class="sc">-</span><span class="fl">0.53</span>, <span class="sc">-</span><span class="fl">0.53</span>, <span class="sc">-</span><span class="fl">0.06</span>, <span class="sc">-</span><span class="fl">0.06</span>, <span class="sc">-</span><span class="fl">0.06</span>, <span class="fl">0.60</span>, <span class="fl">0.60</span>, <span class="fl">0.60</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.08</span>,    <span class="fl">0.02</span>,   <span class="sc">-</span><span class="fl">0.07</span>,  <span class="fl">0.18</span>,   <span class="fl">0.02</span>,   <span class="sc">-</span><span class="fl">0.21</span>,  <span class="fl">0.32</span>,   <span class="fl">0.02</span>,   <span class="sc">-</span><span class="fl">0.40</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> y, <span class="at">x =</span> x, </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">15</span>, <span class="at">col=</span><span class="st">"white"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Negative Tone of the Work Climate (W)"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Team Performance"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>legend.txt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Low Expressivity (W=-0.53)"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Medium Expressivity (W=-0.06)"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                <span class="st">"High Expressivity (W=0.60)"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomleft"</span>, <span class="at">legend=</span>legend.txt, </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x[w<span class="sc">==-</span><span class="fl">0.53</span>], y[w<span class="sc">==-</span><span class="fl">0.53</span>], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x[w<span class="sc">==-</span><span class="fl">0.06</span>], y[w<span class="sc">==-</span><span class="fl">0.06</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x[w<span class="sc">==</span><span class="fl">0.60</span>],  y[w<span class="sc">==</span><span class="fl">0.60</span>],  <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="conditional_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="other-regression-coefficients" class="level1">
<h1>Other regression coefficients</h1>
<p>Consider the coefficients for the variables involved in the interaction. These variables may be identified by looking at the “Product terms key” table. Their coefficients are <code>negtone</code> (<span class="math inline">\(M\)</span>) = -0.44, and <code>negexp</code> (<span class="math inline">\(W\)</span>) = -0.02.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/conditional-process-fit1b.png" class="img-fluid" width="516"></p>
</div>
</div>
<p>As in moderation analysis, each of these coefficients must be interpreted conditional to the other one set to zero. The remaining variables of the model (<span class="math inline">\(X\)</span>, in this case) are maintained constant. For example: considering the set of cases measuring zero in <code>negexp</code> (<span class="math inline">\(W\)</span>) and held constant on <code>dysfunc</code>, a unit increase in <code>negtone</code> (<span class="math inline">\(M\)</span>) corresponds to a 0.44 point lower estimate of <span class="math inline">\(Y\)</span> (-0.44).</p>
<p>A detailed explanation of the rationale for this interpretation was provided in the previous lecture.</p>
</section>
<section id="conditional-direct-and-indirect-effect-model-with-process" class="level1">
<h1>Conditional direct and indirect effect model with process</h1>
<p>It may be difficult to determine in advance whether moderation affects only the direct or indirect effect. So, it can be wise to start with one model including both. If one of the effects is not significant, it is always possible to prune it from the model and fit a new one with the significant effect.</p>
<p>We are going to use the DISASTER dataset to fit a conditional direct and indirect effect model. The model shown in the diagram below is designated in <code>process</code> as <code>model = 8</code>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex2-cond_proc_1.png" class="img-fluid" width="526"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/ex2-cond_proc_2.png" class="img-fluid" width="814"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>disaster <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(<span class="st">"data/disaster.sav"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"donate"</span>, <span class="at">x =</span> <span class="st">"frame"</span>, <span class="at">w =</span> <span class="st">"skeptic"</span>, <span class="at">m =</span> <span class="st">"justify"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">8</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">jn =</span> <span class="dv">1</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot =</span> <span class="dv">1</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.2</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">seed =</span> <span class="dv">280417</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">progress =</span> <span class="dv">0</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> disaster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
               
Model : 8      
    Y : donate 
    X : frame  
    M : justify
    W : skeptic

Sample size: 211

Custom seed: 280417


*********************************************************************** 
Outcome Variable: justify

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.50       0.25       0.66      22.54       3.00     207.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       2.45       0.15      16.45       0.00       2.16       2.75
frame         -0.56       0.22      -2.58       0.01      -0.99      -0.13
skeptic        0.11       0.04       2.76       0.01       0.03       0.18
Int_1          0.20       0.06       3.64       0.00       0.09       0.31

Product terms key:
Int_1  :  frame  x  skeptic      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.05      13.25       1.00     207.00       0.00
----------
Focal predictor: frame (X)
      Moderator: skeptic (W)

Conditional effects of the focal predictor at values of the moderator(s):
     skeptic     effect         se          t          p       LLCI       ULCI
        1.59      -0.24       0.15      -1.62       0.11      -0.54       0.05
        2.80       0.00       0.12       0.01       0.99      -0.23       0.23
        5.20       0.48       0.15       3.21       0.00       0.19       0.78

Moderator value(s) defining Johnson-Neyman significance region(s):
       Value    % below    % above
        1.17       6.64      93.36
        3.93      67.77      32.23

Conditional effect of focal predictor at values of the moderator:
     skeptic     effect         se          t          p       LLCI       ULCI
        1.00      -0.36       0.17      -2.09       0.04      -0.70      -0.02
        1.17      -0.33       0.17      -1.97       0.05      -0.65       0.00
        1.42      -0.28       0.16      -1.77       0.08      -0.58       0.03
        1.84      -0.19       0.14      -1.36       0.17      -0.47       0.09
        2.26      -0.11       0.13      -0.84       0.40      -0.36       0.15
        2.68      -0.02       0.12      -0.19       0.85      -0.26       0.21
        3.11       0.06       0.11       0.55       0.58      -0.16       0.29
        3.53       0.15       0.11       1.31       0.19      -0.07       0.37
        3.93       0.23       0.12       1.97       0.05       0.00       0.46
        3.95       0.23       0.12       1.99       0.05       0.00       0.46
        4.37       0.32       0.12       2.54       0.01       0.07       0.56
        4.79       0.40       0.14       2.94       0.00       0.13       0.67
        5.21       0.49       0.15       3.22       0.00       0.19       0.78
        5.63       0.57       0.17       3.41       0.00       0.24       0.90
        6.05       0.66       0.19       3.54       0.00       0.29       1.02
        6.47       0.74       0.20       3.62       0.00       0.34       1.14
        6.89       0.82       0.22       3.68       0.00       0.38       1.27
        7.32       0.91       0.24       3.72       0.00       0.43       1.39
        7.74       0.99       0.27       3.74       0.00       0.47       1.52
        8.16       1.08       0.29       3.76       0.00       0.51       1.64
        8.58       1.16       0.31       3.77       0.00       0.56       1.77
        9.00       1.25       0.33       3.78       0.00       0.60       1.90

Data for visualizing the conditional effect of the focal predictor:
       frame    skeptic    justify
        0.00       1.59       2.62
        1.00       1.59       2.38
        0.00       2.80       2.75
        1.00       2.80       2.75
        0.00       5.20       3.00
        1.00       5.20       3.48

*********************************************************************** 
Outcome Variable: donate

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.67       0.45       0.97      42.82       4.00     206.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       7.29       0.27      26.64       0.00       6.75       7.83
frame          0.16       0.27       0.60       0.55      -0.37       0.69
justify       -0.92       0.08     -10.98       0.00      -1.09      -0.76
skeptic       -0.04       0.05      -0.91       0.37      -0.14       0.05
Int_1          0.01       0.07       0.22       0.83      -0.12       0.15

Product terms key:
Int_1  :  frame  x  skeptic      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.00       0.05       1.00     206.00       0.83
----------
Focal predictor: frame (X)
      Moderator: skeptic (W)

Data for visualizing the conditional effect of the focal predictor:
       frame    skeptic     donate
        0.00       1.59       4.58
        1.00       1.59       4.76
        0.00       2.80       4.53
        1.00       2.80       4.73
        0.00       5.20       4.43
        1.00       5.20       4.66

*********************************************************************** 
Bootstrapping in progress. Please wait.

**************** DIRECT AND INDIRECT EFFECTS OF X ON Y ****************

Conditional direct effect(s) of X on Y:
     skeptic     effect         se          t          p       LLCI       ULCI
        1.59       0.18       0.18       1.01       0.31      -0.17       0.54
        2.80       0.20       0.14       1.43       0.15      -0.08       0.48
        5.20       0.24       0.19       1.28       0.20      -0.13       0.61

Conditional indirect effects of X on Y:

INDIRECT EFFECT:

frame    -&gt;    justify    -&gt;    donate

     skeptic     Effect     BootSE   BootLLCI   BootULCI
        1.59       0.22       0.14      -0.05       0.51
        2.80      -0.00       0.11      -0.21       0.21
        5.20      -0.45       0.16      -0.75      -0.12

     Index of moderated mediation:
             Index     BootSE   BootLLCI   BootULCI
skeptic      -0.19       0.06      -0.30      -0.06

---

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

Number of bootstraps for percentile bootstrap confidence intervals: 5000

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>We have two regression tables, each in its own panel, the first one with outcome <code>justify</code> and the second one with outcome <code>donate</code>.</p>
<p>The outcome is essentially the same as the previous one. What is different is that both regression tables include an interaction. Data to visualize the two moderator effects is also provided. The pick-a-point and the Johnson-Neyman tables are only provided for the first regression. The second is relative to the direct effect, which implies that moderation translates into a conditional direct effect, which is analyzed in the last part of the output. We can see here the pick-a-point table of both the direct and indirect effect. The index of moderated mediation is provided for the indirect effect.</p>
<p>The interpretation is the same as before, this time applied to both the direct and indirect effect.</p>
<p>In this analysis, we notice that the conditional indirect effect is significant, while the conditional direct effect is not. Therefore, you can opt to simplify the model by removing the moderation of the direct effect. In this specific case, this can be done by switching from <code>model = 8</code> to <code>model = 7</code>.</p>
</section>
<section id="conditional-process-analysis-with-multicategorical-antecedent" class="level1">
<h1>Conditional process analysis with multicategorical antecedent</h1>
<p>When a model includes a multicategorical antecedent, the conditional indirect effect and the conditional direct effect are interpreted relatively to the <em>reference category</em>. In that case we talk of relative conditional indirect effect and relative conditional direct effect.</p>
<p>The model shown below can be fitted using model 8. The mcx=1 option tells <code>process</code> that the <span class="math inline">\(X\)</span> variable is multicategorical. Hayes uses <code>mcx=3</code>, which handles multicategorical variables in a different way. Refer to the book for more information on how <code>process</code> can handle multicategorical variables and the related options (<code>mcx=1</code>, <code>mcx=2</code>, and <code>mcx=3</code>).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/diagram_cond_proc_multicat.png" class="img-fluid" width="478"></p>
</div>
</div>
<p>We fit the model using the “protest” dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>protest <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(<span class="st">"data/protest.sav"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"liking"</span>, <span class="at">x =</span> <span class="st">"protest"</span>,  <span class="at">m =</span> <span class="st">"respappr"</span>, <span class="at">w =</span> <span class="st">"sexism"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">mcx =</span> <span class="dv">1</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">8</span>, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot =</span> <span class="dv">1</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.2</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">progress =</span> <span class="dv">0</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> protest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
                
Model : 8       
    Y : liking  
    X : protest 
    M : respappr
    W : sexism  

Sample size: 129

Random seed: 962884

Coding of categorical X variable for analysis: 
     protest         X1         X2
        0.00       0.00       0.00
        1.00       1.00       0.00
        2.00       0.00       1.00

*********************************************************************** 
Outcome Variable: respappr

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.56       0.32       1.29      11.34       5.00     123.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       6.57       1.20       5.46       0.00       4.19       8.95
X1            -3.78       1.71      -2.21       0.03      -7.16      -0.39
X2            -2.10       1.61      -1.31       0.19      -5.29       1.08
sexism        -0.53       0.23      -2.26       0.03      -0.99      -0.06
Int_1          0.98       0.33       2.98       0.00       0.33       1.63
Int_2          0.73       0.31       2.33       0.02       0.11       1.36

Product terms key:
Int_1  :  X1  x  sexism      
Int_2  :  X2  x  sexism      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.05       4.82       2.00     123.00       0.01
----------
Focal predictor: protest (X)
      Moderator: sexism (W)

Conditional effects of the focal predictor at values of the moderator(s):

Moderator value(s):
                 
sexism       4.25

       effect         se          t          p       LLCI       ULCI
X1       0.38       0.39       0.98       0.33      -0.39       1.15
X2       1.01       0.35       2.88       0.00       0.32       1.71

Test of equality of conditional means
           F        df1        df2          p
        4.28       2.00     123.00       0.02

Estimated conditional means being compared:
     protest   respappr
        0.00       4.32
        1.00       4.70
        2.00       5.33
----------
Moderator value(s):
                 
sexism       5.12

       effect         se          t          p       LLCI       ULCI
X1       1.23       0.25       4.92       0.00       0.74       1.73
X2       1.65       0.25       6.71       0.00       1.17       2.14

Test of equality of conditional means
           F        df1        df2          p
       23.96       2.00     123.00       0.00

Estimated conditional means being compared:
     protest   respappr
        0.00       3.86
        1.00       5.09
        2.00       5.51
----------
Moderator value(s):
                 
sexism       5.90

       effect         se          t          p       LLCI       ULCI
X1       1.99       0.35       5.71       0.00       1.30       2.68
X2       2.22       0.36       6.16       0.00       1.51       2.94

Test of equality of conditional means
           F        df1        df2          p
       22.86       2.00     123.00       0.00

Estimated conditional means being compared:
     protest   respappr
        0.00       3.45
        1.00       5.44
        2.00       5.67

Data for visualizing the conditional effect of the focal predictor:
     protest     sexism   respappr
        0.00       4.25       4.32
        1.00       4.25       4.70
        2.00       4.25       5.33
        0.00       5.12       3.86
        1.00       5.12       5.09
        2.00       5.12       5.51
        0.00       5.90       3.45
        1.00       5.90       5.44
        2.00       5.90       5.67

*********************************************************************** 
Outcome Variable: liking

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
        0.54       0.29       0.82       8.18       6.00     122.00       0.00

Model: 
              coeff         se          t          p       LLCI       ULCI
constant       5.30       1.07       4.95       0.00       3.18       7.42
X1            -2.74       1.39      -1.97       0.05      -5.50       0.01
X2            -2.72       1.29      -2.10       0.04      -5.28      -0.16
respappr       0.37       0.07       5.10       0.00       0.22       0.51
sexism        -0.28       0.19      -1.46       0.15      -0.66       0.10
Int_1          0.54       0.27       2.00       0.05       0.01       1.08
Int_2          0.51       0.26       1.98       0.05       0.00       1.02

Product terms key:
Int_1  :  X1  x  sexism      
Int_2  :  X2  x  sexism      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
X*W       0.03       2.55       2.00     122.00       0.08
----------
Focal predictor: protest (X)
      Moderator: sexism (W)

Conditional effects of the focal predictor at values of the moderator(s):

(These are also the relative conditional direct effects of X on Y.)

Moderator value(s):
                 
sexism       4.25

       effect         se          t          p       LLCI       ULCI
X1      -0.44       0.31      -1.41       0.16      -1.05       0.18
X2      -0.56       0.29      -1.92       0.06      -1.13       0.02

Test of equality of conditional means
           F        df1        df2          p
        1.96       2.00     122.00       0.14

Estimated conditional means being compared:
     protest     liking
        0.00       5.90
        1.00       5.46
        2.00       5.34
----------
Moderator value(s):
                 
sexism       5.12

       effect         se          t          p       LLCI       ULCI
X1       0.03       0.22       0.16       0.88      -0.40       0.47
X2      -0.11       0.23      -0.50       0.62      -0.57       0.34

Test of equality of conditional means
           F        df1        df2          p
        0.29       2.00     122.00       0.75

Estimated conditional means being compared:
     protest     liking
        0.00       5.66
        1.00       5.69
        2.00       5.54
----------
Moderator value(s):
                 
sexism       5.90

       effect         se          t          p       LLCI       ULCI
X1       0.46       0.31       1.45       0.15      -0.16       1.07
X2       0.28       0.33       0.85       0.40      -0.37       0.93

Test of equality of conditional means
           F        df1        df2          p
        1.06       2.00     122.00       0.35

Estimated conditional means being compared:
     protest     liking
        0.00       5.44
        1.00       5.90
        2.00       5.72

Data for visualizing the conditional effect of the focal predictor:
     protest     sexism     liking
        0.00       4.25       5.90
        1.00       4.25       5.46
        2.00       4.25       5.34
        0.00       5.12       5.66
        1.00       5.12       5.69
        2.00       5.12       5.54
        0.00       5.90       5.44
        1.00       5.90       5.90
        2.00       5.90       5.72

*********************************************************************** 
Bootstrapping in progress. Please wait.

**************** DIRECT AND INDIRECT EFFECTS OF X ON Y ****************

Relative conditional direct effect(s) of X on Y:
       sexism     effect         se          t          p       LLCI       ULCI
X1       4.25      -0.44       0.31      -1.41       0.16      -1.05       0.18
X1       5.12       0.03       0.22       0.16       0.88      -0.40       0.47
X1       5.90       0.46       0.31       1.45       0.15      -0.16       1.07
X2       4.25      -0.56       0.29      -1.92       0.06      -1.13       0.02
X2       5.12      -0.11       0.23      -0.50       0.62      -0.57       0.34
X2       5.90       0.28       0.33       0.85       0.40      -0.37       0.93

Relative conditional indirect effects of X on Y:

INDIRECT EFFECT:

protest    -&gt;    respappr    -&gt;    liking

       sexism     Effect     BootSE   BootLLCI   BootULCI
X1       4.25       0.14       0.16      -0.19       0.47
X1       5.12       0.45       0.13       0.21       0.73
X1       5.90       0.73       0.21       0.34       1.16

     Index of moderated mediation:
            Index     BootSE   BootLLCI   BootULCI
sexism       0.36       0.16       0.06       0.70


---
       sexism     Effect     BootSE   BootLLCI   BootULCI
X2       4.25       0.37       0.15       0.11       0.69
X2       5.12       0.61       0.15       0.33       0.91
X2       5.90       0.82       0.23       0.40       1.28

     Index of moderated mediation:
            Index     BootSE   BootLLCI   BootULCI
sexism       0.27       0.15      -0.01       0.58

---

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

Number of bootstraps for percentile bootstrap confidence intervals: 5000

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
<p>The output can be interpreted on the basis of the same principles discussed for multicategorical moderation models, and conditional direct and indirect effect models. The output is a mix of outputs from these models.</p>
<section id="brief-recap-on-the-interpretation-of-multicategorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="brief-recap-on-the-interpretation-of-multicategorical-variables">Brief recap on the interpretation of multicategorical variables</h2>
<p>There is only one fundamental principle to be taken into account in the interpretation of multicategorical models. The g categories of a multicategorical variable are divided into g-1 dichotomous variables and a reference category. The newly created dichotomous variables represent differences between a category and the reference category.</p>
<p>In this case, the multicategorical variable PROTEST includes <span class="math inline">\(g = 3\)</span> categories (<span class="math inline">\(X=0\)</span>, <span class="math inline">\(X=1\)</span>, <span class="math inline">\(X=2\)</span>), which are divided into <span class="math inline">\(g-1 = 2\)</span> dichotomous variables (<span class="math inline">\(X1\)</span> <span class="math inline">\(X=1\)</span>, and <span class="math inline">\(X2\)</span> <span class="math inline">\(X=2\)</span>) and a reference category (<span class="math inline">\(X0 X=0\)</span>). The newly created dichotomous variables <span class="math inline">\(X1\)</span> and <span class="math inline">\(X2\)</span> represent differences (in some estimates) between a category and the reference category (<span class="math inline">\(X1 = X1 - X0\)</span>; <span class="math inline">\(X2 = X2 - X0\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"img/table_cond_proc_multicat.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="img/table_cond_proc_multicat.png" class="img-fluid" width="754"></p>
</div>
</div>
<p>For example, consider the interaction term:</p>
<ul>
<li>In a model with continuous X, the interaction terms (<em>Int</em>) would quantify <em>changes in the conditional effect of X on Y</em> for a <em>one-unit change in X</em>.</li>
<li>In a model with dichotomous X, <em>one-unit change in X</em> means switching from <span class="math inline">\(X=0\)</span> to <span class="math inline">\(X=1\)</span>, and the interaction terms would quantify the <em>difference between X1 and X0 in their conditional effect on Y</em>.</li>
<li>We know that a multicategorical variable is treated as <em>g-1</em> dichotomous ones, therefore the interpretation is similar to that of dichotomous variables. In this case, the interaction term <em>Int_1</em> quantifies the difference <em>between X1 and X0 in their conditional effect on Y</em>, and <em>Int_2</em> quantifies the <em>difference between X2 and X0 in their conditional effect on Y</em>. Therefore, they are relative conditional effects.</li>
</ul>
</section>
</section>
<section id="relative-conditional-effect" class="level1">
<h1>Relative conditional effect</h1>
<p>We already know how to detect conditional effects in the regression equations. Here, there are two conditional effects. The first is for <span class="math inline">\(X1\)</span>, which represents the difference between <span class="math inline">\(X1\)</span> and <span class="math inline">\(X0\)</span> in their conditional effect on <span class="math inline">\(Y\)</span>, and the second for <span class="math inline">\(X2\)</span>.</p>
<p>First, we write the equations based on the regression coefficients of two outcomes <code>justify</code> (<span class="math inline">\(M\)</span>) and <code>donate</code> (<span class="math inline">\(Y\)</span>).</p>
<p><span class="math display">\[M = i_M + a_1X_1 + a_2X_2 + a_3W + a_4X_1W + a_5X_2W + e_M\]</span> <span class="math display">\[Y = i_Y + c'_1X_1 + c'_2X_2 + c'_3W + c'_4X_1W + c'_5X_2W + bM + e_Y\]</span></p>
<p>Next, we proceed as usual by grouping and factoring out the like variables.</p>
<p><span class="math display">\[Y = c'_1X_1 + c'_2X_2 + c'_3W + c'_4X_1W + c'_5X_2W + bM + e_Y\]</span> <span class="math display">\[\hat Y = (c'_1 + c'_4W)X_1 + (c'_2 + c'_5W)X_2 + c'_3W + bM\]</span> <span class="math display">\[\theta{X_1 \to Y} = c'_1 + c'_4W)\]</span> <span class="math display">\[\theta{X_2 \to Y} = c'_2 + c'_5W\]</span></p>
<p><span class="math display">\[M = i_M + a_1X_1 + a_2X_2 + a_3W + a_4X_1W + a_5X_2W + e_M\]</span> <span class="math display">\[M = i_M + (a_1 + a_4W)X_1 + (a_2 + a_5W)X_2 + a_3W + e_M\]</span> <span class="math display">\[\theta{X_1 \to M} = a_1 + a_4W\]</span> <span class="math display">\[\theta{X_2 \to M} = a_2 + a_5W\]</span></p>
<p>The table Conditional effects of the focal predictor at values of the moderator(s) uses these function to calculate the relative conditional effect at different levels of the moderator (<span class="math inline">\(W\)</span> = <code>sexism</code>). For instance, for <code>sexism</code> = 4.25, the relative conditional effect represented by <span class="math inline">\(X1\)</span> is:</p>
<p><span class="math display">\[\theta{X_1 \to M} = a_1 + a_4W\]</span> <span class="math display">\[\theta{X_1 \to M} = -3.78 + 0.98*4.25 = 0.385\]</span></p>
<p>The table shows p-values and confidence intervals to verify the statistical significance of the relative conditional effects.</p>
<p>The output also reports the estimated conditional means being compared, which are the means of the dependent variable (respectively <span class="math inline">\(M\)</span> or <span class="math inline">\(Y\)</span>, depending on the model) in the different categories (<code>protest</code>= 0, 1, and 2), holding the moderator constant at a certain value. The table Test of equality of conditional means reports the statistical test of the equality of these means (i.e., is there any evidence of statistically significant differences between any of those means?).</p>
</section>
<section id="conditional-direct-and-indirect-relative-effects" class="level1">
<h1>Conditional direct and indirect relative effects</h1>
<p>Relative conditional effects are used to compute the relative conditional direct and indirect effects.</p>
<p>The indirect effect is the product <span class="math inline">\(ab\)</span> of the two paths linking the antecedent variable to the mediator (<span class="math inline">\(a\)</span>), and the mediator to the dependent variable (<span class="math inline">\(b\)</span>). In the case of a multicategorical antecedent, the <span class="math inline">\(a\)</span> path is represented by two or more <em>relative conditional effects</em>.</p>
<p>In this case the <em>relative conditional effects</em> are <span class="math inline">\(\theta{X_1 \to M}\)</span> and <span class="math inline">\(\theta{X_2 \to M}\)</span>. Therefore, the relative conditional indirect effects can be computed as <span class="math inline">\(a * \theta{X_1 \to M}\)</span> and <span class="math inline">\(a * \theta{X_2 \to M}\)</span>. Various values of the moderator <span class="math inline">\(M\)</span> are then plugged into these functions to test the effect in the pick-a-point approach. The same is for the relative conditional direct effect. The pick-a-point tables are shown in the last part of the output. They can be interpreted as usual, but keeping in mind that each variables (for instance <span class="math inline">\(X1\)</span> and <span class="math inline">\(X2\)</span>) represent the the difference between a category and the reference one (in this case between <span class="math inline">\(X1\)</span> and <span class="math inline">\(X0\)</span>, or between <span class="math inline">\(X2\)</span> and <span class="math inline">\(X0\)</span>) in their effect on <span class="math inline">\(Y\)</span> through the mediator <span class="math inline">\(M\)</span> at different levels of the moderator.</p>
</section>
<section id="appendix-assumptions-and-robust-methods" class="level1">
<h1>Appendix: Assumptions and robust methods</h1>
<p>During the first part of the course, we learned about regression models. We said that they have assumptions and that their results are reliable only when those assumptions are respected.</p>
<p>It is, therefore, necessary to check the assumptions before interpreting the results. If one or more of them are not fulfilled, it may be possible to take steps to solve the problem.</p>
<p>First, let’s recap the assumptions of regression models:</p>
<ul>
<li><p><strong>Linearity</strong>: There exists a linear relationship between each predictor variable and the response variable.</p></li>
<li><p><strong>No Multicollinearity</strong>: None of the predictor variables are highly correlated with each other.</p></li>
<li><p><strong>No Outliers</strong>: None of the data points are too different from the others, resulting in a strong influence on the estimate.</p></li>
<li><p><strong>Independence</strong>: Observations are independent (a problem arising particularly with time series data).</p></li>
<li><p><strong>Homoscedasticity</strong>: The residuals have constant variance at every point in the linear model.</p></li>
<li><p><strong>Normality</strong>: The residuals of the model are normally distributed.</p></li>
</ul>
<p><code>process</code> implements methods that help to solve issues that may arise with assumptions. Unfortunately, however, it does not provide instruments to test them. Therefore, let’s see how to check the assumptions.</p>
<section id="check-the-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-the-assumptions">Check the assumptions</h2>
<p>We can test the assumptions of our models based on what we learned in the first part of the course. There, we learned how to fit multiple regression models in R using the <code>lm</code> function. We also learned how to test the assumptions by visually inspecting some plots.</p>
<p>The procedure includes the following steps:</p>
<ol type="1">
<li>Fit your mediation, moderation, or conditional process model using <code>process</code>.</li>
<li>Check the regression tables and fit the same models in R, using the <code>lm</code> function.</li>
<li>Use R to check the assumptions.</li>
<li>Take possible steps to address potential problems related to assumptions.</li>
</ol>
</section>
<section id="check-regression-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-regression-assumptions">Check regression assumptions</h2>
<p>We illustrate the method by a conditional process model that includes both mediating and moderating effects. Therefore, it is representative of any cases you may come across.</p>
<section id="step-1-fit-the-model-with-process" class="level4">
<h4 class="anchored" data-anchor-id="step-1-fit-the-model-with-process">STEP 1: Fit the model with PROCESS</h4>
<p>As a first step, let’s fit the model in <code>process</code>. We can omit <code>jn</code> and <code>plot</code> options which are not relevant in this case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"perform"</span>, <span class="at">x =</span> <span class="st">"dysfunc"</span>, <span class="at">m =</span> <span class="st">"negtone"</span>, <span class="at">w =</span> <span class="st">"negexp"</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">14</span>, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.5</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">seed=</span><span class="dv">42517</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">boot =</span> <span class="dv">5000</span>, <span class="co"># number of bootstraps </span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">progress =</span> <span class="dv">0</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> teams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
               
Model : 14     
    Y : perform
    X : dysfunc
    M : negtone
    W : negexp 

Sample size: 60

Custom seed: 42517


*********************************************************************** 
Outcome Variable: negtone

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
     0.43841    0.19220    0.22683   13.79991    1.00000   58.00000    0.00046

Model: 
              coeff         se          t          p       LLCI       ULCI
constant    0.02568    0.06176    0.41585    0.67905   -0.09794    0.14930
dysfunc     0.61975    0.16683    3.71482    0.00046    0.28580    0.95371

*********************************************************************** 
Outcome Variable: perform

Model Summary: 
           R       R-sq        MSE          F        df1        df2          p
     0.55856    0.31199    0.20146    6.23504    4.00000   55.00000    0.00033

Model: 
              coeff         se          t          p       LLCI       ULCI
constant   -0.01188    0.05853   -0.20293    0.83994   -0.12918    0.10542
dysfunc     0.36606    0.17782    2.05854    0.04429    0.00969    0.72243
negtone    -0.43575    0.13055   -3.33774    0.00152   -0.69738   -0.17412
negexp     -0.01918    0.11741   -0.16340    0.87080   -0.25448    0.21611
Int_1      -0.51697    0.24092   -2.14576    0.03632   -0.99979   -0.03414

Product terms key:
Int_1  :  negtone  x  negexp      

Test(s) of highest order unconditional interaction(s):
       R2-chng          F        df1        df2          p
M*W    0.05760    4.60429    1.00000   55.00000    0.03632
----------
Focal predictor: negtone (M)
      Moderator: negexp (W)

Conditional effects of the focal predictor at values of the moderator(s):
      negexp     effect         se          t          p       LLCI       ULCI
    -0.53080   -0.16134    0.20875   -0.77290    0.44289   -0.57969    0.25701
    -0.06000   -0.40473    0.13566   -2.98344    0.00424   -0.67660   -0.13286
     0.60000   -0.74593    0.16259   -4.58792    0.00003   -1.07176   -0.42010

*********************************************************************** 
Bootstrapping in progress. Please wait.

**************** DIRECT AND INDIRECT EFFECTS OF X ON Y ****************

Direct effect of X on Y:
      effect         se          t          p       LLCI       ULCI
     0.36606    0.17782    2.05854    0.04429    0.00969    0.72243

Conditional indirect effects of X on Y:

INDIRECT EFFECT:

dysfunc    -&gt;    negtone    -&gt;    perform

      negexp     Effect     BootSE   BootLLCI   BootULCI
    -0.53080   -0.09999    0.14961   -0.37028    0.23944
    -0.06000   -0.25083    0.11861   -0.49280   -0.03543
     0.60000   -0.46229    0.17057   -0.80677   -0.14881

     Index of moderated mediation:
            Index     BootSE   BootLLCI   BootULCI
negexp   -0.32039    0.18907   -0.76118   -0.04209

---

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

Number of bootstraps for percentile bootstrap confidence intervals: 5000

W values in conditional tables are the 16th, 50th, and 84th percentiles.</code></pre>
</div>
</div>
</section>
<section id="step-2-check-the-regression-tables-and-fit-the-models-in-r" class="level4">
<h4 class="anchored" data-anchor-id="step-2-check-the-regression-tables-and-fit-the-models-in-r">STEP 2: Check the regression tables and fit the models in R</h4>
<p>The results consists of two regression tables, one for each dependent variable. The former is the model of <code>negtone</code> and the latter of <code>perform</code>. So we’re talking about two regression models.</p>
<p>We fit exactly the same models using R, plugging the variables shown in each table in the <code>lm</code> function. Note that the second model is moderated, thus includes a interaction term: <code>Int_1</code>. From the “Product term key” table you can see that the interaction is between the variables <code>negtone</code> and <code>negexp</code>: <code>negtone x negexp</code>. To create this interaction term into <code>lm</code>, you just put the variables into the function using the multiplication symbol <span class="math inline">\(*\)</span>:<span class="math inline">\(negtone * negexp\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(negtone <span class="sc">~</span> dysfunc, <span class="at">data =</span> teams)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(perform <span class="sc">~</span> dysfunc <span class="sc">+</span> negtone <span class="sc">+</span> negexp <span class="sc">+</span> negtone <span class="sc">*</span> negexp, <span class="at">data =</span> teams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare the outputs to be sure that the models are exactly the same:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = negtone ~ dysfunc, data = teams)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.99459 -0.26346 -0.06103  0.23478  1.59585 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.02568    0.06176   0.416 0.679053    
dysfunc      0.61975    0.16683   3.715 0.000459 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4763 on 58 degrees of freedom
Multiple R-squared:  0.1922,    Adjusted R-squared:  0.1783 
F-statistic:  13.8 on 1 and 58 DF,  p-value: 0.000459</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = perform ~ dysfunc + negtone + negexp + negtone * 
    negexp, data = teams)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.03038 -0.31679 -0.00591  0.26235  0.98591 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.01188    0.05853  -0.203  0.83994   
dysfunc         0.36606    0.17782   2.059  0.04429 * 
negtone        -0.43575    0.13055  -3.338  0.00152 **
negexp         -0.01918    0.11741  -0.163  0.87080   
negtone:negexp -0.51697    0.24092  -2.146  0.03632 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4488 on 55 degrees of freedom
Multiple R-squared:  0.312, Adjusted R-squared:  0.2619 
F-statistic: 6.235 on 4 and 55 DF,  p-value: 0.0003276</code></pre>
</div>
</div>
</section>
<section id="step-3-use-r-to-check-the-assumptions." class="level4">
<h4 class="anchored" data-anchor-id="step-3-use-r-to-check-the-assumptions.">STEP 3: Use R to check the assumptions.</h4>
<p>We start with the <em>plot</em> function to visually check if the assumptions are respected for both models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="conditional_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="conditional_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can observe that the red line is roughly horizontal in the two plots to the left, which is good (linearity assumption).</p>
<p>The points are also more or less randomly distributed around the red line (homoskedasticity assumption), which is fine. In case of doubt, a formal test of homoskedasticity is the Breusch-Pagan Test. It is implemented in the function <code>bptest</code> of the library <code>lmtest</code>. As long as the test is not statistically significant, no obvious heteroskedastic problems are present.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m1
BP = 2.6223, df = 1, p-value = 0.1054</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m2
BP = 4.491, df = 4, p-value = 0.3436</code></pre>
</div>
</div>
<p>The graph in the upper right panel shows points approximately on a diagonal line, which is also good (normality hypothesis). In case of doubts, a formal test of normality is the Shapiro-Wilk’s test. It needs to be applied to the residuals of the model. Normality is presumed unless the test is statistically significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(m1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  m1$residuals
W = 0.95575, p-value = 0.02927</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(m2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  m2$residuals
W = 0.98974, p-value = 0.896</code></pre>
</div>
</div>
<p>The bottom right chart is mainly used to verify the presence of outliers. They are “influential observations” whose presence significantly affects the model results. They can be found off the dashed lines (undetected, which is fine).</p>
<p>Independence of observations is mainly a problem of time series data. In case of doubt, a formal test of this assumption is the Durbin-Watson test. It is implemented in the function <code>dwtest</code> of the <code>lmtest</code> package.The assumption is satisfied if the Durbin-Watson statistic (DW) is about equal to 2, and the test is statistically non-significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">dwtest</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  m1
DW = 1.8549, p-value = 0.2854
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">dwtest</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  m2
DW = 1.9281, p-value = 0.3762
alternative hypothesis: true autocorrelation is greater than 0</code></pre>
</div>
</div>
<p>No multicollinearity applies only to regression models with more than one independent variable (i.e.&nbsp;multiple regression models). It can be formally verified by calculating the Pearson correlation coefficient between the independent variables and the index VIF (“Variance Inflation Factor”). The correlation should include all the independent variables, including the interaction term, if present. The interaction term needs to be calculated manually (this is only the product between the variables). For the assumption to be met the correlation has not to be too high and the VIF scores have to be well below 10 (e.g., in a recent publication it can be read that <em>“None of the correlations among the independent variables exceeded r=|0.58| while the largest variance inflation factor (VIF) was VIF=1.60, indicating that multicollinearity does not limit the regression model”</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># just keep the independent variables </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> teams[, <span class="fu">c</span>(<span class="st">"dysfunc"</span>, <span class="st">"negtone"</span>, <span class="st">"negexp"</span>)]</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># since we have an interaction term, we have to compute also this interaction</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>negtone_x_negexp <span class="ot">&lt;-</span> dat<span class="sc">$</span>negtone <span class="sc">*</span> dat<span class="sc">$</span>negexp</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearsons' correlation</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      dysfunc   negtone       negexp negtone_x_negexp
dysfunc           1.000000000 0.4384057 -0.006841573      -0.03631275
negtone           0.438405680 1.0000000  0.084626603       0.26881696
negexp           -0.006841573 0.0846266  1.000000000       0.40127021
negtone_x_negexp -0.036312754 0.2688170  0.401270214       1.00000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>there are higher-order terms (interactions) in this model
consider setting type = 'predictor'; see ?vif</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       dysfunc        negtone         negexp negtone:negexp 
      1.279174       1.377851       1.193402       1.315798 </code></pre>
</div>
</div>
</section>
<section id="step-4-take-possible-steps-to-address-potential-problems-related-to-assumptions." class="level4">
<h4 class="anchored" data-anchor-id="step-4-take-possible-steps-to-address-potential-problems-related-to-assumptions.">STEP 4: Take possible steps to address potential problems related to assumptions.</h4>
<p>Issues with linearity may be fixed through transformations (e.g., log-transforming the variables).</p>
<p>Outliers have to be thoroughly inspected. If in doubt, you can perform robust regression in R and check whether the results are more or less the same as those of <code>process</code>. Robust regression attempts to dampen the influence of outlying cases in order to provide a better fit to the majority of the data. A good practical tutorial on robust regression is available here: <a href="https://www.youtube.com/watch?v=qte9ASvgElI" class="uri">https://www.youtube.com/watch?v=qte9ASvgElI</a>.</p>
<p>In case of serious multicollinearity problems (based on the VIF index) you can omit one of the highly correlated variables.</p>
<p>Finally, in case of hetersoskedasticity problems you can request <code>process</code> to use <em>heteroskedasticity-consistent (HC) standard errors</em>. The available options are: HC0, HC1, HC2, HC3, and HC4. You only need to add <code>hc=4</code> (or a different number between 1 and 4) to the <code>process</code> function. Heteroskedasticity-consistent (HC) standard errors were also discussed in the first part of the course on regression models. Models with both standard errors and heteroskedasticity-consistent standard errors can be fitted for comparison even if hetersoskedasticity issues are not obvious.</p>
<p>Hayes and Cay wrote:</p>
<blockquote class="blockquote">
<p>“(…) we argue that an HC estimator, preferably HC3 or HC4, should be routinely used in linear regression models, if it is not used as the default method of standard error estimation, researchers would be well advised to at least double-check the results from the use of the OLSE estimator against the results obtained with an HC estimator, to make sure that conclusions are not compromised by heteroskedasticity”.</p>
<p>Hayes, A. F., &amp; Cai, L. (2007). <a href="https://link.springer.com/content/pdf/10.3758/BF03192961.pdf">Using heteroskedasticity-consistent standard error estimators in OLS regression: An introduction and software implementation</a>. <em>Behavior research methods</em>, 39(4), 709-722.</p>
</blockquote>
<p>To treat normality problems, bootstrapping can be used to compute confidence intervals for regression coefficients. You only have to add <code>modelbt = 1</code> to the PROCESS function. The coefficients with the bootstrap confidence intervals will appear at the bottom of the result. They can be interpreted as usual: if the range overlaps zero, there is not enough evidence to consider it statistically significant.</p>
<p>These confidence intervals are not the same as those reported in the regression tables at the beginning of the output. The latter is based on hypotheses of normality, and are symmetrical around the coefficient. The percentile bootstrap confidence intervals are rather “asymmetric”. They are not based on a normal theoretical distribution, but of the empirical distribution as given in the sample (which is almost never perfectly normal).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">y =</span> <span class="st">"perform"</span>, <span class="at">x =</span> <span class="st">"dysfunc"</span>, <span class="at">m =</span> <span class="st">"negtone"</span>, <span class="at">w =</span> <span class="st">"negexp"</span>,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">model =</span> <span class="dv">14</span>, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">jn =</span> <span class="dv">1</span>, </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot =</span> <span class="dv">1</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">decimals =</span> <span class="fl">10.5</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">seed =</span> <span class="dv">42517</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">hc =</span> <span class="dv">4</span>, <span class="co"># heteroskedasticity-consistent standard errors hc4</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">modelbt =</span> <span class="dv">1</span>, <span class="co"># bootstrap CI for regression coefficients </span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">boot =</span> <span class="dv">5000</span>, </span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">progress =</span> <span class="dv">0</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> teams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
********************* PROCESS for R Version 4.0.1 ********************* 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
               
Model : 14     
    Y : perform
    X : dysfunc
    M : negtone
    W : negexp 

Sample size: 60

Custom seed: 42517


*********************************************************************** 
Outcome Variable: negtone

Model Summary: 
           R       R-sq        MSE     F(HC4)        df1        df2          p
     0.43841    0.19220    0.22683    5.29928    1.00000   58.00000    0.02494

Model: 
              coeff    se(HC4)          t          p       LLCI       ULCI
constant    0.02568    0.06129    0.41899    0.67677   -0.09701    0.14838
dysfunc     0.61975    0.26922    2.30202    0.02494    0.08084    1.15866

*********************************************************************** 
Outcome Variable: perform

Model Summary: 
           R       R-sq        MSE     F(HC4)        df1        df2          p
     0.55856    0.31199    0.20146    3.49092    4.00000   55.00000    0.01304

Model: 
              coeff    se(HC4)          t          p       LLCI       ULCI
constant   -0.01188    0.05975   -0.19879    0.84316   -0.13162    0.10787
dysfunc     0.36606    0.23092    1.58522    0.11865   -0.09672    0.82883
negtone    -0.43575    0.15693   -2.77669    0.00749   -0.75025   -0.12125
negexp     -0.01918    0.11244   -0.17062    0.86515   -0.24453    0.20616
Int_1      -0.51697    0.32049   -1.61303    0.11246   -1.15926    0.12532

Product terms key:
Int_1  :  negtone  x  negexp      

Test(s) of highest order unconditional interaction(s):
       R2-chng     F(HC4)        df1        df2          p
M*W    0.05760    2.60186    1.00000   55.00000    0.11246
----------
Focal predictor: negtone (M)
      Moderator: negexp (W)

Data for visualizing the conditional effect of the focal predictor:
     negtone     negexp    perform
    -0.45000   -0.53080    0.08360
    -0.03500   -0.53080    0.01664
     0.52240   -0.53080   -0.07329
    -0.45000   -0.06000    0.18409
    -0.03500   -0.06000    0.01613
     0.52240   -0.06000   -0.20947
    -0.45000    0.60000    0.32497
    -0.03500    0.60000    0.01541
     0.52240    0.60000   -0.40037

*********************************************************************** 
Bootstrapping in progress. Please wait.

**************** DIRECT AND INDIRECT EFFECTS OF X ON Y ****************

Direct effect of X on Y:
      effect    se(HC4)          t          p       LLCI       ULCI
     0.36606    0.23092    1.58522    0.11865   -0.09672    0.82883

Conditional indirect effects of X on Y:

INDIRECT EFFECT:

dysfunc    -&gt;    negtone    -&gt;    perform

      negexp     Effect     BootSE   BootLLCI   BootULCI
    -0.53080   -0.09999    0.14961   -0.37028    0.23944
    -0.06000   -0.25083    0.11861   -0.49280   -0.03543
     0.60000   -0.46229    0.17057   -0.80677   -0.14881

     Index of moderated mediation:
            Index     BootSE   BootLLCI   BootULCI
negexp   -0.32039    0.18907   -0.76118   -0.04209

---

********** BOOTSTRAP RESULTS FOR REGRESSION MODEL PARAMETERS **********

Outcome variable: negtone

              Coeff   BootMean     BootSE   BootLLCI   BootULCI
constant    0.02568    0.02816    0.05982   -0.08350    0.14707
dysfunc     0.61975    0.63196    0.22578    0.21552    1.09547
----------
Outcome variable: perform

              Coeff   BootMean     BootSE   BootLLCI   BootULCI
constant   -0.01188   -0.01190    0.05835   -0.12698    0.10469
dysfunc     0.36606    0.32286    0.19229   -0.09397    0.66792
negtone    -0.43575   -0.42239    0.13201   -0.65435   -0.12768
negexp     -0.01918   -0.02401    0.10235   -0.22884    0.17457
Int_1      -0.51697   -0.53510    0.24224   -1.06997   -0.10944

******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

Number of bootstraps for percentile bootstrap confidence intervals: 5000

W values in conditional tables are the 16th, 50th, and 84th percentiles.
 
NOTE: A heteroscedasticity consistent standard error and covariance matrix estimator was used. </code></pre>
</div>
</div>
</section>
</section>
<section id="custom-models" class="level2">
<h2 class="anchored" data-anchor-id="custom-models">Custom models</h2>
<p><code>process</code> implements several pre-programmed models to perform a wide range of common analyses. Advanced users can customize templates and even build new templates with more complex relationships. The details are given in the appendix of Hayes’ book.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="//moderation.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Moderation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="//conditional.html" class="pagination-link">
        <span class="nav-page-text">Conditional process</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Nicola Righetti</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.nicolarighetti.net">
      <i class="bi bi-wordpress" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nicolarighetti">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://mas.to/@nicolarighetti">
      <i class="bi bi-mastodon" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/nicolarighetti79/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>