<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mediation, Moderation, and Conditional Process Analysis with R - EDA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="//EDA.html" rel="next">
<link href="//Rintro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Mediation, Moderation, and Conditional Process Analysis with R</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./introduction.html" aria-current="page">
 <span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Rintro.html">
 <span class="menu-text">Getting started with R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./EDA.html">
 <span class="menu-text">Exploratory Data Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./regression.html">
 <span class="menu-text">Regression Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mediation.html">
 <span class="menu-text">Mediation Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./moderation.html">
 <span class="menu-text">Moderation Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conditional.html">
 <span class="menu-text">Conditional Process Analysis</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">EDA</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction.html" class="sidebar-item-text sidebar-link">Introduction</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Rintro.html" class="sidebar-item-text sidebar-link">Getting started with R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./EDA.html" class="sidebar-item-text sidebar-link active">Exploratory Data Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression.html" class="sidebar-item-text sidebar-link">Regression Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mediation.html" class="sidebar-item-text sidebar-link">Mediation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./moderation.html" class="sidebar-item-text sidebar-link">Moderation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./conditional.html" class="sidebar-item-text sidebar-link">Conditional Process Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#sample-size-and-data-preview" id="toc-sample-size-and-data-preview" class="nav-link" data-scroll-target="#sample-size-and-data-preview">Sample size and data preview</a></li>
  <li><a href="#measure-of-central-tendency" id="toc-measure-of-central-tendency" class="nav-link" data-scroll-target="#measure-of-central-tendency">Measure of central tendency</a>
  <ul class="collapse">
  <li><a href="#the-mean" id="toc-the-mean" class="nav-link" data-scroll-target="#the-mean">The Mean</a></li>
  <li><a href="#frequency-distributions" id="toc-frequency-distributions" class="nav-link" data-scroll-target="#frequency-distributions">Frequency distributions</a></li>
  <li><a href="#five-number-summary" id="toc-five-number-summary" class="nav-link" data-scroll-target="#five-number-summary">Five-Number Summary</a></li>
  <li><a href="#boxplot" id="toc-boxplot" class="nav-link" data-scroll-target="#boxplot">Boxplot</a></li>
  <li><a href="#histogram" id="toc-histogram" class="nav-link" data-scroll-target="#histogram">Histogram</a></li>
  <li><a href="#bar-plot" id="toc-bar-plot" class="nav-link" data-scroll-target="#bar-plot">Bar plot</a></li>
  </ul></li>
  <li><a href="#measures-of-spread" id="toc-measures-of-spread" class="nav-link" data-scroll-target="#measures-of-spread">Measures of Spread</a>
  <ul class="collapse">
  <li><a href="#variance" id="toc-variance" class="nav-link" data-scroll-target="#variance">Variance</a></li>
  <li><a href="#standard-deviation" id="toc-standard-deviation" class="nav-link" data-scroll-target="#standard-deviation">Standard Deviation</a></li>
  </ul></li>
  <li><a href="#standardization-and-z-scores" id="toc-standardization-and-z-scores" class="nav-link" data-scroll-target="#standardization-and-z-scores">Standardization and z-scores</a></li>
  <li><a href="#correlation-and-prediction" id="toc-correlation-and-prediction" class="nav-link" data-scroll-target="#correlation-and-prediction">Correlation and prediction</a>
  <ul class="collapse">
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation">Correlation</a></li>
  <li><a href="#pearsons-correlation-coefficient-pearsons-r" id="toc-pearsons-correlation-coefficient-pearsons-r" class="nav-link" data-scroll-target="#pearsons-correlation-coefficient-pearsons-r">Pearsons’ correlation coefficient (Pearsons’ R)</a>
  <ul class="collapse">
  <li><a href="#pearsons-r-and-covariance" id="toc-pearsons-r-and-covariance" class="nav-link" data-scroll-target="#pearsons-r-and-covariance">Pearsons’ R and covariance</a></li>
  <li><a href="#pearsons-r-interpretation" id="toc-pearsons-r-interpretation" class="nav-link" data-scroll-target="#pearsons-r-interpretation">Pearsons’ R interpretation</a></li>
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">Scatterplots</a></li>
  </ul></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions">Predictions</a></li>
  </ul></li>
  <li><a href="#readings-and-excercises" id="toc-readings-and-excercises" class="nav-link" data-scroll-target="#readings-and-excercises">Readings and excercises</a>
  <ul class="collapse">
  <li><a href="#notes-on-the-glbwarm-data-set-and-excercises" id="toc-notes-on-the-glbwarm-data-set-and-excercises" class="nav-link" data-scroll-target="#notes-on-the-glbwarm-data-set-and-excercises">Notes on the GLBWARM data set and excercises</a>
  <ul class="collapse">
  <li><a href="#excercise-1" id="toc-excercise-1" class="nav-link" data-scroll-target="#excercise-1">Excercise 1</a></li>
  <li><a href="#excercise-2" id="toc-excercise-2" class="nav-link" data-scroll-target="#excercise-2">Excercise 2</a></li>
  <li><a href="#excercise-3" id="toc-excercise-3" class="nav-link" data-scroll-target="#excercise-3">Excercise 3</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">EDA</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<p>At the end of this section you will understand the following concepts, know the R functions to calculate/create the following statistical measures/plots, and be able to interpret them:</p>
<ul>
<li>Sample size and data set preview</li>
<li>Frequency distributions of a variable</li>
<li>Histograms, boxplots, bar plots</li>
<li>Measures of central tendency and measures of spread</li>
<li>Standardization and z-scores</li>
</ul>
</section>
<section id="sample-size-and-data-preview" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-and-data-preview">Sample size and data preview</h2>
<p>When starting to work with a new data set, the first step is to describe its general characteristics and those of its variables. This includes:</p>
<ul>
<li>describing the number of cases in the data set (the <strong>sample size</strong>)</li>
<li>examining the types of variables</li>
<li>and computing descriptive statistics such as the mean and standard deviation.</li>
</ul>
<p>A research report typically contains information on the data set and variables.</p>
<p>We already learned how to perform some of these operations by using the following functions:</p>
<ul>
<li><strong>dim()</strong> to find the number of rows of the data set, which corresponds to the number of cases (<strong>sample size</strong>) in a common and well structured data set.</li>
<li><strong>str()</strong> or <strong>glimpse()</strong> (in the package <em>tidiverse</em>) to look at the types of variables included in the data set</li>
<li><strong>head()</strong> to see a preview of the data set</li>
<li><strong>View()</strong> to view the data set in a separate window (warning: not reccomended if the data set is huge, since it can freeze your computer)</li>
</ul>
<p>Let’s see an example, using the global warming study data set (glbwarm).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the glbwarm data set</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>glbwarm <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/glbwarm.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It’s a well-organized data set. Each line describes a case. The sample size can therefore be calculated by counting the number of rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(glbwarm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 815   7</code></pre>
</div>
</div>
<p>The sample size is 815 (<strong>n = 815</strong>, where <strong>n</strong> stands for the number of cases included in the sample).</p>
<p>We can also see that there are 7 variables. We can now look at their type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0     ✔ purrr   1.0.1
✔ tibble  3.1.8     ✔ dplyr   1.1.0
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.3     ✔ forcats 1.0.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(glbwarm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 815
Columns: 7
$ govact   &lt;dbl&gt; 3.6, 5.0, 6.6, 1.0, 4.0, 7.0, 6.8, 5.6, 6.0, 2.6, 1.4, 5.6, 7…
$ posemot  &lt;dbl&gt; 3.67, 2.00, 2.33, 5.00, 2.33, 1.00, 2.33, 4.00, 5.00, 5.00, 1…
$ negemot  &lt;dbl&gt; 4.67, 2.33, 3.67, 5.00, 1.67, 6.00, 4.00, 5.33, 6.00, 2.00, 1…
$ ideology &lt;int&gt; 6, 2, 1, 1, 4, 3, 4, 5, 4, 7, 6, 4, 2, 4, 5, 2, 6, 4, 2, 4, 4…
$ age      &lt;int&gt; 61, 55, 85, 59, 22, 34, 47, 65, 50, 60, 71, 60, 71, 59, 32, 3…
$ sex      &lt;int&gt; 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0…
$ partyid  &lt;int&gt; 2, 1, 1, 1, 1, 2, 1, 1, 2, 3, 2, 1, 1, 1, 1, 1, 2, 3, 1, 3, 2…</code></pre>
</div>
</div>
<p>The glimpse function also includes a preview of the data set, but a clearer preview is displayd with <em>head()</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(glbwarm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  govact posemot negemot ideology age sex partyid
1    3.6    3.67    4.67        6  61   0       2
2    5.0    2.00    2.33        2  55   0       1
3    6.6    2.33    3.67        1  85   1       1
4    1.0    5.00    5.00        1  59   0       1
5    4.0    2.33    1.67        4  22   1       1
6    7.0    1.00    6.00        3  34   0       2</code></pre>
</div>
</div>
</section>
<section id="measure-of-central-tendency" class="level2">
<h2 class="anchored" data-anchor-id="measure-of-central-tendency">Measure of central tendency</h2>
<p><a href="https://en.wikipedia.org/wiki/Descriptive_statistics">Descriptive statistics</a> are used to describe and summarize variables of a data set.</p>
<p>Typically, there are two general types of statistics that are used to describe data: <strong>Measures of central tendency</strong> and <strong>Measures of spread</strong>.</p>
<p><strong>Measures of central tendency</strong> include: - <strong>Mode</strong>: the most frequent score in our data set - <strong>Median</strong>: the middle score for a set of data that has been arranged in order of magnitude - <strong>Mean</strong>: the sum of all the values in the data set divided by the number of values in the data set.</p>
<p>A clear description of the different measures can be found <a href="https://statistics.laerd.com/statistical-guides/measures-central-tendency-mean-mode-median.php">here</a>.</p>
<section id="the-mean" class="level3">
<h3 class="anchored" data-anchor-id="the-mean">The Mean</h3>
<p>In this course we’ll focus on the mean (or average). This is the most popular and well known measure of central tendency, and it is used in linear regression modeling.</p>
<p>The mean itself is essentially a model of a data set. One of its important properties is that it minimises error in the prediction of any one value in the data set. In other terms, lacking better predictors, the mean is the best predictor of a value in the data set.</p>
<p>In R, you can calculate the mean of a variable by the function <strong>mean()</strong> (reminder: to access a variable in the data set, that is to say, a column of a data.frame, use the dollar sign):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(glbwarm<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.5362</code></pre>
</div>
</div>
<p>The mean age of people in the sample is 49.5362. To round off decimals, you can add the function <strong>round()</strong>. It takes two main arguments: a number (or a function that returns a number) to be rounded off, and an integer that tells R how many decimals you want to include.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(glbwarm<span class="sc">$</span>age), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.54</code></pre>
</div>
</div>
<p>This is equivalent to creating an object <em>mean_age</em> representing the output of the function mean (i.e., the mean age), and then rounding it off.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(glbwarm<span class="sc">$</span>age)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mean_age, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.54</code></pre>
</div>
</div>
</section>
<section id="frequency-distributions" class="level3">
<h3 class="anchored" data-anchor-id="frequency-distributions">Frequency distributions</h3>
<p>The frequency distribution of a variable is an overview of its values and the number of times they occur (i.e., their frequency).</p>
<p>The distributions can be continuous or discrete, depending on the type of variable. The distribution of a variable is summarized by the <a href="https://en.wikipedia.org/wiki/Five-number_summary">five-number summary</a>, and graphically, by histograms and box plots (for continuous or discrete variables) and bar charts (for categorical variables).</p>
<ul>
<li><p><strong>Discrete variables</strong> have <strong>discrete distributions</strong>. Such a variable can only take specific values. Count data (non-negative integers), are an example: for instance, the number of friends on Facebook. In the <em>glbwarm</em> data set, the variable ideology is measured on a discrete scale ranging from 1 to 7.</p></li>
<li><p><strong>Discrete variables</strong> can also represent <strong>categorical data</strong>. Categorical data expresses qualitative dimensions of a phenomenon. For instance, city names (Vienna, London, Verona), or ordered categorical values (low, medium, high). Categorical data can be represented by numbers, but they should not be conceived as mathematical objects, but as “names” or ordered categories. Categorical variables that can take on only two values are called <strong>dichotomous</strong> variables (e.g., sex, if you only differentiate between males and females). In the data set <em>glbwarm</em>, the variable “sex” is represented as a dichotomous variable.</p></li>
<li><p><strong>Continuous variables</strong> have <strong>continuous distributions</strong>. This kind of variable can assume one of an infinite (uncountable) number of different values. Continuous variables are represented by real numbers. Temperature or velocity are an example. In the data set <em>glbwarm</em>, the variable “govact” is represented as a continuous variable.</p></li>
</ul>
</section>
<section id="five-number-summary" class="level3">
<h3 class="anchored" data-anchor-id="five-number-summary">Five-Number Summary</h3>
<p>data set</p>
<p>A numerical description of the distribution is provided by the function <strong>summary()</strong>, which gives the <strong>five-number summary</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glbwarm<span class="sc">$</span>ideology)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   3.000   4.000   4.083   5.000   7.000 </code></pre>
</div>
</div>
<p>The five-number summary includes the mean, the median, minimum and maximum values, the first and third quartiles. <a href="https://en.wikipedia.org/wiki/Quartile">Quartiles</a> are cut points dividing the range of values of the variable into four parts, or quarters, of more-or-less equal size (25%, 25%, 25%, 25%). The <a href="https://en.wikipedia.org/wiki/Median">median</a> is the value separating the lower 50% from the upper 50% of the distribution.</p>
</section>
<section id="boxplot" class="level3">
<h3 class="anchored" data-anchor-id="boxplot">Boxplot</h3>
<p>The same information of a five-number summary is graphically displayed by the <a href="https://en.wikipedia.org/wiki/Box_plot">boxplot</a>, also called <em>box-and-whisker plot</em>. The “box” represent the 1st and 3rd quartile, the central line is the median, the “whiskers” represent the maximumn and minimum.</p>
<p>The points above and below the whiskers are <a href="https://en.wikipedia.org/wiki/Outlier">outliers</a>, data points that differ significantly from other observations. Since they are so different they are difficult to predict. Moreover, they can bias the estimates of a linear regression models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the argument "main" to add a title</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(glbwarm<span class="sc">$</span>govact, <span class="at">main =</span> <span class="st">"Ideology"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="histogram" class="level3">
<h3 class="anchored" data-anchor-id="histogram">Histogram</h3>
<p>Another way to show the distribution of a variable is by means of an <a href="https://en.wikipedia.org/wiki/Histogram">histogram</a>, using the function <strong>hist()</strong>.</p>
<p>The function can be used to show the frequency distribution of values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use "main" tp change the title, and "xlab" to change the name of the x axis</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(glbwarm<span class="sc">$</span>govact, </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"GOVACT (GLBWARM data set)"</span>, <span class="at">xlab =</span> <span class="st">"govact"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As well as the probability distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># you can use the argument "col" to change the color</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to see the available colors, run the following command in the console: colors() </span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(glbwarm<span class="sc">$</span>govact, <span class="at">probability =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"GOVACT (GLBWARM data set)"</span>, <span class="at">xlab =</span> <span class="st">"govact"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"slategrey"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(glbwarm<span class="sc">$</span>govact, <span class="at">adjust =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When dealing with continuous variables, may want to add a line to overlay a <a href="https://www.statisticshowto.com/density-curve-examples/">density curve</a> on the histogram, to aproximate the shape of the distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(glbwarm<span class="sc">$</span>govact, <span class="at">probability =</span> <span class="cn">TRUE</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"GOVACT (GLBWARM data set)"</span>, <span class="at">xlab =</span> <span class="st">"govact"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"slategrey"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this is to add a line of the "density"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the argument "lwd" sets the width of the line</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(glbwarm<span class="sc">$</span>govact), </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"steelblue1"</span>, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># this is to add a more smoothed (simpler and more aproximated) density curve </span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># the argument "lty" sets the type of line</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(glbwarm<span class="sc">$</span>govact, <span class="at">adjust =</span> <span class="dv">2</span>), </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="st">"lightblue"</span>, </span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">lwd =</span> <span class="dv">3</span>, </span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">lty =</span> <span class="st">"dotted"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="bar-plot" class="level3">
<h3 class="anchored" data-anchor-id="bar-plot">Bar plot</h3>
<p>Histograms and box plot are used to represent the distribution of numerical variables, such as continuous and discrete variables. For categorical variables, a bar graph is used in place.</p>
<p>For instance, the histogram of the dichotomous categorical variable “sex”, is not appropriate. It only takes on the values 0 and 1, but they are not numbers (0 = male, 1 = female) and there is nothing in between them (e.g., 0, 0.1, 0.2, …, 1).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(glbwarm<span class="sc">$</span>sex, <span class="at">main =</span> <span class="st">"SEX (categorical dichotomous variable)"</span>, <span class="at">xlab =</span> <span class="st">"sex"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The appropriate way to represent the frequency distribution of categorical variables is the bar chart (or bar plot). The corresponding R function is <strong>barplot()</strong>.</p>
<p>It takes as argument a table with the frequency for each of the modalities of the category (i.e., a table with the number of males and females in the sample). The function <strong>table()</strong> returns the frequency of the variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(glbwarm<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
417 398 </code></pre>
</div>
</div>
<p>This function can be used as the main argument of the function <strong>barplot()</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(glbwarm<span class="sc">$</span>sex),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Observations by SEX"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"0 = Male 1 = Female"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="measures-of-spread" class="level2">
<h2 class="anchored" data-anchor-id="measures-of-spread">Measures of Spread</h2>
<p><strong>Measures of spread</strong> describe how similar or varied the set of observed values are for a particular variable. Measures of spread include the range, quartiles and the interquartile range, variance and standard deviation.</p>
<p>For example, the interquartile range is the difference between the third and first quartile and is represented by the size of the “box” in a boxplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(glbwarm<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even more relevant are variance and standard deviation.</p>
<section id="variance" class="level3">
<h3 class="anchored" data-anchor-id="variance">Variance</h3>
<p><strong>Variance</strong> (represented as <span class="math inline">\(s^2\)</span> when computed on a sample, as in this case), is a measure of dispersion that quantifies how spread the values of a variable are from the mean (the average value of the variable), or in other terms, of how much they vary (“variance”).</p>
<p>The formula for variance is:</p>
<p><span class="math display">\[s^2 =  \frac{\sum_{i=1}^{n} (x_i-\bar x)^2}{n-1}\]</span></p>
<p>Capital sigma <span class="math inline">\(\sum\)</span> is the summation symbol, <span class="math inline">\((x_i-\bar x)\)</span> is the deviation (i.e., the difference) of each value <span class="math inline">\(i\)</span> of <span class="math inline">\(X\)</span> from the <em>mean</em> of <span class="math inline">\(X\)</span> (<span class="math inline">\(\bar x\)</span>, the mean or average of the variables), and <span class="math inline">\(n\)</span> is the sample size. In R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(glbwarm<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 266.6937</code></pre>
</div>
</div>
</section>
<section id="standard-deviation" class="level3">
<h3 class="anchored" data-anchor-id="standard-deviation">Standard Deviation</h3>
<p><strong>Standard deviation</strong> (represented as <span class="math inline">\(s\)</span> when computed on a sample, as in this case) is a related, and more commonly used, measure of dispersion. A low standard deviation indicates that the values of a variable tend to be close to its average, while a high standard deviation indicates that the values are spread out over a wider range. It is the square root of the variance:</p>
<p><span class="math display">\[s = \sqrt \frac{\sum (x_i-\bar x)^2}{n-1}\]</span></p>
<p>In R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(glbwarm<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.33076</code></pre>
</div>
</div>
</section>
</section>
<section id="standardization-and-z-scores" class="level1">
<h1>Standardization and z-scores</h1>
<p>Besides measuring the spread of a variable, standard deviation is used for standardizing variables.</p>
<p>Standardization is a procedure that transforms the original data (“raw data”) in the so-called <strong>z-scores</strong>. Z-scores are are values expressed in standardized units by using the average and the standard deviation:</p>
<p><span class="math display">\[Z = \frac{x_i - \bar x}{s}\]</span></p>
<p>A way to think about standardization, is considering it as the interpretation of values relatively to their own distribution.</p>
<p>The average of a standardized variable is always zero, below-average values are negative and above-average values are positive.</p>
<p>In R, standarization is provided by the function <strong>scale()</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>zscores_age <span class="ot">&lt;-</span> <span class="fu">scale</span>(glbwarm<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(zscores_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A classic example of the utility of z-scores typically goes like this. Suppose two sections of a statistics course are being taught. John is a student in section A and Mary is a student in section B. On the final exam for the course, John receives a raw score of 80 out of 100 (i.e., 80%). Mary, on the other hand, earns a score of 70 out of 100 (i.e., 70%).</p>
<p>At first glance, it may appear that John was more successful on his final exam. However, scores, considered absolutely, do not allow us a comparison of each student’s score relative to their class distributions. For instance, if the mean in John’s class was equal to 85% with a standard deviation of 2, John’s z-score is:</p>
<p><span class="math display">\[Z = \frac{x_i - \bar x}{\sigma} =  \frac{80 - 85}{2} = -2.5\]</span></p>
<p>Suppose that in Mary’s class, the mean was equal to 65% also with a standard deviation of 2. Mary’s zscore is thus:</p>
<p><span class="math display">\[Z = \frac{x_i - \bar x}{\sigma} =  \frac{70 - 65}{2} = 2.5\]</span></p>
<p>As we can see, relative to their particular distributions, Mary greatly outperformed John.</p>
<p>Z-scores are often used with reference to the <strong>standard normal distribution</strong>. In this case, 68%, 95%, and 99.7% of the values lie within one, two, and three standard deviations of the mean, respectively. It is considered statistically unlikely that a value is 2 standard deviations either side of the mean. We’ll encounter again the normal distribution and the 2 standard deviation threshold when we’ll take statistical inference into consideration.</p>
</section>
<section id="correlation-and-prediction" class="level1">
<h1>Correlation and prediction</h1>
<p>In the first section we used statistical measures and charts to describe variables. In this section we’ll learn to assess the relationships between two variables.</p>
<p>At the end of this unit you will understand the following concepts, be able to interpret them, and know the R functions to calculate and create the related statistical measures and plots:</p>
<ul>
<li>Pearson’s correlation</li>
<li>Scatterplot</li>
<li>Prediction</li>
</ul>
<section id="correlation" class="level2">
<h2 class="anchored" data-anchor-id="correlation">Correlation</h2>
<p>data set</p>
<p>Correlation is a <strong>statistical relationship</strong>, whether causal or not, between two variables.</p>
<p>Two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are said to be correlated when they show a systematic association, so that knowing the values of one variable enables the <strong>prediction</strong> of the values of the other.</p>
<p><strong>Correlation analysis</strong> permits to identify this relationship and to quantify its strength.</p>
</section>
<section id="pearsons-correlation-coefficient-pearsons-r" class="level2">
<h2 class="anchored" data-anchor-id="pearsons-correlation-coefficient-pearsons-r">Pearsons’ correlation coefficient (Pearsons’ R)</h2>
<p>The <em>Pearson’s product moment correlation</em>, also known as <strong>Pearson’s r</strong>, is an important measure of correlation.</p>
<p>It is also the foundation of most of the linear regression methods discussed in this course. Indeed, it can be used to quantify the <strong>linear association</strong> (or relationship) between two quantitative variables, a quantitative and a dichotomous variable, as well as between two dichotomous variables.</p>
<p>In linear association, the direction and rate of change in one variable are constant with respect to changes in the other variable. For example, in a perfect linear association between two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, an increase of 1 point in <span class="math inline">\(X\)</span> corresponds to an increase of 1 point in <span class="math inline">\(Y\)</span>.</p>
<p>A linear relationship describes a straight-line relationship between two variables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="img/correlation_examples.png" class="img-fluid" width="1280"></p>
</div>
</div>
<section id="pearsons-r-and-covariance" class="level3">
<h3 class="anchored" data-anchor-id="pearsons-r-and-covariance">Pearsons’ R and covariance</h3>
<p>Pearson’s r is based on the formalization of the idea of calculating the <em>ratio</em> between the degree to which <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> vary <em>together</em>, and the degree to which <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> vary <em>separately</em>, in order to find how much “co-variation” they share.</p>
<p><span class="math display">\[r = \frac{degree-to-which-X-and-Y-vary-together}{degree-to-which-X-and-Y-vary-separately}\]</span></p>
<p>The idea of covariation is mathematically expressed by <strong>covariance</strong> (<span class="math inline">\(cov\)</span>), which is at the heart of virtually all statistical methods. The Pearson’s <span class="math inline">\(r\)</span> is a <strong>standardized measure of covariance</strong>.</p>
<p>Covariance is based on <strong>variance</strong> (<span class="math inline">\(s^2\)</span>):</p>
<p><span class="math display">\[s^2 =  \frac{\sum_{i=1}^{n} (x_i-\bar x)^2}{n-1}\]</span></p>
<p>More precisely, covariance is a <em>measure of the joint variability of two variables</em>, and is calculated as the product of the <strong>variance</strong> of the variables:</p>
<p><span class="math display">\[ cov = \frac{\sum_{i=1}^{n} (x_i-\bar x) (y_i-\bar y)}{n-1}\]</span></p>
<p>The covariance can be positive, negative, or equal to zero, and gives a measure of the linear correlation between variables.</p>
<p>So, why do we need Pearson’s <em>r</em>? Because covariance is a measure that depends on the unit of measurement of the variables, while it is preferable to have a <strong>standard</strong> measure, meaningful independently of each specific data set.</p>
<p>Standardizazion of covariance is obtained by dividing the covariance <span class="math inline">\(cov\)</span> by the <strong>product of the standard deviations</strong> of the variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. This product represents the <strong>total amount of variation possible</strong>.</p>
<p>Thanks to the denominator, which represents the total amount of variation possible for the specific couple of variables, <span class="math inline">\(r\)</span> <strong>is always constrained between 1 and -1</strong> for <em>any</em> variable expressed in any unit of measure. The extent to which the covariation <span class="math inline">\(cov_{XY}\)</span> accounts for all of the possible variation (<span class="math inline">\(SD_XSD_Y\)</span>) is the extent to which <span class="math inline">\(r\)</span> approximates <span class="math inline">\(|1|\)</span> (negative -1, or positive +1).</p>
<p><span class="math display">\[ r = \frac{cov_{XY}}{SD_XSD_Y}\]</span></p>
<p>In R, the correlation coefficient is computed with the function <strong>cor</strong>. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(glbwarm<span class="sc">$</span>govact, glbwarm<span class="sc">$</span>negemot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5777458</code></pre>
</div>
</div>
</section>
<section id="pearsons-r-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="pearsons-r-interpretation">Pearsons’ R interpretation</h3>
<p>Pearson’s correlation coefficient can be interpreted as follows:</p>
<ul>
<li><p>The <strong>sign (+/-)</strong> corresponds to the <em>direction</em> of the association between X and Y:</p>
<ul>
<li><strong>positive linear association</strong> (+): the higher X, the higher Y;</li>
<li><strong>negative linear association</strong> (-): the higher X, the lower Y.</li>
</ul></li>
<li><p><span class="math inline">\(r\)</span> is close to <strong>zero</strong> when the association is null or nonlinear</p></li>
<li><p>The closer <span class="math inline">\(r\)</span> is to <span class="math inline">\(|1|\)</span> (+1 or -1), the <strong>stronger</strong> the linear association.</p></li>
</ul>
<p>There are different rule of thumbs for the interpretation of the Pearson’s correlation. For example, Mike Allen (2017), <em>The SAGE Encyclopedia of Communication Research Methods</em> (p.&nbsp;269) suggests the following:</p>
<ul>
<li>0.00-0.19 Negligible correlation</li>
<li>0.20-0.39 Weak correlation</li>
<li>0.40-0.59 Fair correlation</li>
<li>0.60-0.79 Moderate correlation</li>
<li>0.80-1.00 Strong correlation</li>
</ul>
</section>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">Scatterplots</h3>
<p><strong>Scatterplot</strong> is the common method for visually exploring and representing the correlation between two variables is scatterplot.</p>
<p>“A scatter plot is a type of plot or mathematical diagram using Cartesian coordinates to display values for typically two variables for a set of data. If the points are coded (color/shape/size), one additional variable can be displayed. The data are displayed as a collection of points, each having the value of one variable determining the position on the horizontal axis and the value of the other variable determining the position on the vertical axis” (<a href="https://en.wikipedia.org/wiki/Scatter_plot">Wikipedia</a>).</p>
<p>To create a scatterplot in R it is possible to use the function <strong>plot()</strong>. It takes two argoments: x (the first variable) and y (the second variable). The argument <em>pch</em> changes the shape of the points: see more details <a href="https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/points.html">here</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glbwarm<span class="sc">$</span>govact, glbwarm<span class="sc">$</span>posemot,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"govact"</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"posemot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The scatter plot shows the direction of the association.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>) <span class="co"># simulating data</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>Yp <span class="ot">&lt;-</span> X <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">sd=</span><span class="fl">0.5</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>Yn <span class="ot">&lt;-</span> <span class="sc">-</span>Yp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-paged.print="false">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, Yp, <span class="at">main =</span> <span class="st">"Positive Association"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, Yn, <span class="at">main =</span> <span class="st">"Negative Association"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="864"></p>
</div>
</div>
</section>
</section>
<section id="predictions" class="level2">
<h2 class="anchored" data-anchor-id="predictions">Predictions</h2>
<p>When there is a correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, using <span class="math inline">\(X_j\)</span> to estimate <span class="math inline">\(Y_j\)</span> produces estimates that are more accurate than if one were to merely estimate <span class="math inline">\(Y_j = \bar Y\)</span> (the average value of <span class="math inline">\(Y\)</span>) for every case in the data.</p>
<blockquote class="blockquote">
<p>Given a variable <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> of a data set of size n, the subscripts “j” in <span class="math inline">\(X_j\)</span> and <span class="math inline">\(Y_j\)</span>, indicates the j case. It can be any one of the n cases, but the same for both the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables. In other words, it indicates the measures of the case j on the variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</blockquote>
<p>Pearson’s <em>r</em> provides an estimate as to how many <em>standard deviations (Z) from the sample mean</em> on <span class="math inline">\(Y\)</span> a case is, given how many standard deviations from the sample mean the case is on <span class="math inline">\(X\)</span>. More formally:</p>
<p><span class="math display">\[\hat Z_{Y_j} = r_{XY}Z_{X_j}\]</span></p>
<p>where <span class="math inline">\(\hat Z_{Y_j}\)</span> is the estimated value of <span class="math inline">\(Z_{Y_j}\)</span>.</p>
<ul>
<li>For instance, a person who is one-half of a standard deviation above the mean (<span class="math inline">\(Z_X = 0.5\)</span>) in negative emotions, is estimated to be <span class="math inline">\(\hat{Z} = 0.578(0.5) = 0.289\)</span> standard deviations from the mean in his or her support for government action.</li>
<li>The sign of <span class="math inline">\(\hat{Z_Y}\)</span> is positive, meaning that this person is estimated to be above the sample mean (i.e., more supportive than average).</li>
<li>Similarly, someone who is two standard deviations below the mean (<span class="math inline">\(Z_X = −2\)</span>) in negative emotions is estimated to be <span class="math inline">\(Z_Y = 0.578(−2) = −1.156\)</span> standard deviations from the mean in support for government action.</li>
<li>In this case, <span class="math inline">\(\hat{Z_Y}\)</span> is negative, meaning that such a person is estimated to be below the sample mean in support for government action (i.e., less supportive than average).</li>
</ul>
<p><strong>Estimates</strong> of Y from X are <strong>expectations</strong> extracted from what is known about the association between X and Y.</p>
<p>In statistics, expectations are never perfectly met, but we have a numerical means of gauging how close are to reality.</p>
<p>In our case, that gauge is the size of Pearson’s <em>r</em>. The closer it is to +/- 1, the more consistent those expectations are with the reality of the data.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="EDA_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="readings-and-excercises" class="level1">
<h1>Readings and excercises</h1>
<ul>
<li>Review the content of the class</li>
<li>Read chapter 2, pp.&nbsp;29-34</li>
</ul>
<section id="notes-on-the-glbwarm-data-set-and-excercises" class="level2">
<h2 class="anchored" data-anchor-id="notes-on-the-glbwarm-data-set-and-excercises">Notes on the GLBWARM data set and excercises</h2>
<p>GLBWARM is a data set collected from 815 residents of the United States (417 female, 398 male) who expressed a willingness to participate in online surveys in exchange for various incentives. The sampling procedure was designed such that the respondents roughly represent the U.S. population.</p>
<p>The data set contains a variable constructed from how each participant responded to five questions about the extent to which he or she supports various policies or actions by the U.S. government to mitigate the threat of global climate change.</p>
<p>Examples include:</p>
<ul>
<li>“How much do you support or oppose increasing government investment for developing alternative energy like biofuels, wind, or solar by 25%?”</li>
<li>“How much do you support or oppose creating a ‘Cap and Trade’ policy that limits greenhouse gases said to cause global warming?”</li>
</ul>
<p>Response options were scaled from “Strongly opposed” (coded 1) or “Strongly support” (7), with intermediate labels to denote intermediate levels of support. An index of support for government action to reduce climate change was constructed for each person by averaging responses to the five questions (GOVACT in the data file).</p>
<p>The data set also contains a variable quantifying participants’ negative emotional responses to the prospect of climate change. This variable was constructed using participants’ responses to a question that asked them to indicate how frequently they feel each of three emotions when thinking about global warming: “worried,” “alarmed,” and “concerned.” Response options included “not at all,” “slightly,” “a little bit,” “some,” “a fair amount,” and “a great deal.” These responses were numerically coded 1 to 6, respectively, and each participant’s responses were averaged across all three emotions to produce a measure of negative emotions about climate change (NEGEMOT in the data file). This variable is scaled such that higher scores reflect feeling stronger negative emotions.</p>
<section id="excercise-1" class="level3">
<h3 class="anchored" data-anchor-id="excercise-1">Excercise 1</h3>
<p>Display the correlation between the variables <em>negemot</em> and <em>govact</em> using a scatterplot.</p>
<p>Based on the plot, can you tell if there is a correlation between the two variables?</p>
<p>In your opinion, is there a strong correlation between these variables?</p>
</section>
<section id="excercise-2" class="level3">
<h3 class="anchored" data-anchor-id="excercise-2">Excercise 2</h3>
<p>Use the function <em>cor()</em> to calculate the correlation between the variables <em>negemot</em> and <em>govact</em> in the glbwarm data set.</p>
<p>Based on the Pearsons’s r coefficient, is there a strong correlation between these variables?</p>
</section>
<section id="excercise-3" class="level3">
<h3 class="anchored" data-anchor-id="excercise-3">Excercise 3</h3>
<p>Consider the variables <em>tnews</em> and <em>age</em> in the <strong>glbwarm</strong> data set:</p>
<ul>
<li>Visualize the association using a scatterplot</li>
<li>Calculate the Pearsons’s r correlation</li>
<li>Write a comment to interpret the results</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="//Rintro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Getting started with R</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="//EDA.html" class="pagination-link">
        <span class="nav-page-text">EDA</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Nicola Righetti</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.nicolarighetti.net">
      <i class="bi bi-wordpress" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nicolarighetti">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://mas.to/@nicolarighetti">
      <i class="bi bi-mastodon" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/nicolarighetti79/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>