<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Nicola Righetti, PhD">

<title>MMCP - Regression analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="//regression.html" rel="next">
<link href="//EDA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MMCP</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./introduction.html" aria-current="page">
 <span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Rintro.html">
 <span class="menu-text">R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./EDA.html">
 <span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./regression.html">
 <span class="menu-text">Regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mediation.html">
 <span class="menu-text">Mediation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./moderation.html">
 <span class="menu-text">Moderation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conditional.html">
 <span class="menu-text">Conditional</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Regression analysis</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction.html" class="sidebar-item-text sidebar-link">Introduction</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Rintro.html" class="sidebar-item-text sidebar-link">Getting started with R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./EDA.html" class="sidebar-item-text sidebar-link">Exploratory Data Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression.html" class="sidebar-item-text sidebar-link active">Regression Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mediation.html" class="sidebar-item-text sidebar-link">Mediation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./moderation.html" class="sidebar-item-text sidebar-link">Moderation Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./conditional.html" class="sidebar-item-text sidebar-link">Conditional Process Analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning Goals</a></li>
  <li><a href="#what-is-a-model" id="toc-what-is-a-model" class="nav-link" data-scroll-target="#what-is-a-model">What is a model?</a>
  <ul class="collapse">
  <li><a href="#example-the-mean-as-a-simple-data-model" id="toc-example-the-mean-as-a-simple-data-model" class="nav-link" data-scroll-target="#example-the-mean-as-a-simple-data-model">Example: the mean as a simple data model</a></li>
  <li><a href="#the-mean-in-regression-analysis" id="toc-the-mean-in-regression-analysis" class="nav-link" data-scroll-target="#the-mean-in-regression-analysis">The mean in regression analysis</a></li>
  <li><a href="#components-of-a-statistical-model" id="toc-components-of-a-statistical-model" class="nav-link" data-scroll-target="#components-of-a-statistical-model">Components of a statistical model</a></li>
  </ul></li>
  <li><a href="#linear-models" id="toc-linear-models" class="nav-link" data-scroll-target="#linear-models">Linear models</a></li>
  <li><a href="#the-equation-form" id="toc-the-equation-form" class="nav-link" data-scroll-target="#the-equation-form">The equation form</a></li>
  <li><a href="#multiple-linear-regression-model" id="toc-multiple-linear-regression-model" class="nav-link" data-scroll-target="#multiple-linear-regression-model">Multiple linear regression model</a></li>
  <li><a href="#elements-of-the-linear-model-equation" id="toc-elements-of-the-linear-model-equation" class="nav-link" data-scroll-target="#elements-of-the-linear-model-equation">Elements of the linear model equation</a>
  <ul class="collapse">
  <li><a href="#the-index-j" id="toc-the-index-j" class="nav-link" data-scroll-target="#the-index-j">The index j</a></li>
  <li><a href="#intercept" id="toc-intercept" class="nav-link" data-scroll-target="#intercept">Intercept</a></li>
  <li><a href="#regression-coefficient" id="toc-regression-coefficient" class="nav-link" data-scroll-target="#regression-coefficient">Regression coefficient</a></li>
  <li><a href="#error" id="toc-error" class="nav-link" data-scroll-target="#error">Error</a></li>
  </ul></li>
  <li><a href="#fit-a-linear-regression-model-with-r" id="toc-fit-a-linear-regression-model-with-r" class="nav-link" data-scroll-target="#fit-a-linear-regression-model-with-r">Fit a linear regression model with R</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple linear regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple linear regression</a></li>
  <li><a href="#interpretation-of-the-output" id="toc-interpretation-of-the-output" class="nav-link" data-scroll-target="#interpretation-of-the-output">Interpretation of the output</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit"><strong>Goodness-of-fit</strong></a></li>
  <li><a href="#estimates" id="toc-estimates" class="nav-link" data-scroll-target="#estimates"><strong>Estimates</strong></a>
  <ul class="collapse">
  <li><a href="#intercept-1" id="toc-intercept-1" class="nav-link" data-scroll-target="#intercept-1"><strong>Intercept</strong></a></li>
  <li><a href="#coefficients-1" id="toc-coefficients-1" class="nav-link" data-scroll-target="#coefficients-1"><strong>Coefficients</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#residuals-and-assumptions" id="toc-residuals-and-assumptions" class="nav-link" data-scroll-target="#residuals-and-assumptions">Residuals and assumptions</a>
  <ul class="collapse">
  <li><a href="#check-the-assumptions" id="toc-check-the-assumptions" class="nav-link" data-scroll-target="#check-the-assumptions">Check the assumptions</a></li>
  </ul></li>
  <li><a href="#reading-resources-exercises" id="toc-reading-resources-exercises" class="nav-link" data-scroll-target="#reading-resources-exercises">Reading, resources, exercises</a>
  <ul class="collapse">
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings">Readings</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  <li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1">Exercises 1</a></li>
  <li><a href="#exercises-2-optional" id="toc-exercises-2-optional" class="nav-link" data-scroll-target="#exercises-2-optional">Exercises 2 (optional)</a>
  <ul class="collapse">
  <li><a href="#description-of-the-data-set" id="toc-description-of-the-data-set" class="nav-link" data-scroll-target="#description-of-the-data-set">Description of the data set</a></li>
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise">Exercise</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Regression analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Nicola Righetti, PhD </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="learning-goals" class="level1">
<h1>Learning Goals</h1>
<ul>
<li>Understand the concept of statistical model</li>
<li>Understand the concept of linear regression model</li>
<li>Know how to fit a linear regression model with R</li>
<li>Know how to interpret the results of linear regression models</li>
<li>Understand the concept of goodness of fit and know how to evaluate it</li>
<li>Understand the assumptions of the linear regression model and know how to evaluate them</li>
</ul>
</section>
<section id="what-is-a-model" class="level1">
<h1>What is a model?</h1>
<ul>
<li><p>A <strong>model</strong> is an <em>approximate and simplified representation</em> of a real phenomenon which captures its most distinctive features (i.e., trends, patterns, etc).</p></li>
<li><p>A <strong>mathematical model</strong> is a model built from mathematical objects, such as numbers, formulas, equations, and so on.</p></li>
<li><p>A <strong>statistical model</strong> is a special kind of mathematical model, informed by data and built to predict phenomena characterized by a <em>certain degree of uncertainty</em>, and/or to test out hypotheses about how the system being modeled actually works.</p></li>
</ul>
<section id="example-the-mean-as-a-simple-data-model" class="level2">
<h2 class="anchored" data-anchor-id="example-the-mean-as-a-simple-data-model">Example: the mean as a simple data model</h2>
<p>For example, we can consider the mean as a simple data model. Indeed, it can be conceived as a synthetic, simplified, and approximate representation of the distribution of a variable. It is a mathematical model since it is a number, and a statistical model since it is informed by data and implies a certain level of uncertainty. Actually, the mean is only a rough representation of a variable. In fact, single values can be more or less in line with the mean. The mean represents “on average” the different values of a variable. We can also quantify the uncertainty in this type of simple model thanks to the standard deviation. The standard deviation can be intended as an approximate measure of the average distance between the data points and the mean. A low standard deviation indicates that the values are clustered close to the mean, making the mean an excellent model. However, a high standard deviation means that the values are generally distant from the mean, making the mean a relatively poor model of the variable.</p>
<p>For example, let’s take a group of four friends whose monthly income is 1,000 euros, 1,500 euros, 4,000 euros, and 7,000 euros respectively. Using the mean to build a simple model of their income, we can see that the mean income is EUR 3,375. However, this is not a very good approximation of the income of these people if we want to use it to predict the income of each member of the group. The standard deviation is high (SD = 2,750 euros), indicating a great deal of variability and uncertainty. On average, the members’ income is 2,750 euros far from the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>income <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">1500</span>, <span class="dv">4000</span>, <span class="dv">7000</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3375</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2750</code></pre>
</div>
</div>
<p>Let’s now consider a group of four friends who have monthly incomes of EUR 1,000, EUR 1,500, EUR 1,300, and EUR 900 respectively. Using the mean to create a simple model of their income, we can see that the mean income is EUR 1,175 with a low standard deviation (SD = 275). This group is relatively homogeneous regarding their income, and therefore, the mean serves as a reliable model for predicting the income of each member.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>income <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">1500</span>, <span class="dv">1300</span>, <span class="dv">900</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1175</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 275.3785</code></pre>
</div>
</div>
</section>
<section id="the-mean-in-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="the-mean-in-regression-analysis">The mean in regression analysis</h2>
<p>In linear regression, the mean is particularly important:</p>
<ul>
<li>It is used as a <strong>baseline</strong> against which to compare the utility of the model. Linear regression modeling attempts to identify variables (independent variables) that help explain/predict another variable (the dependent variable or outcome) better than the outcome variable’s average. The model using the mean that is used as a baseline is also called the <strong>null model</strong>.</li>
<li>The linear regression model attempts to predict the mean value of a variable, given one or more other variables and assumes a linear relationship between the predictors and the outcome.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/linear_model_gaussian_errors.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Image from: Le Gratiet, L., Iooss, B., Blatman, G., Browne, T., Cordeiro, S., &amp; Goursaud, B. (2017). Model assisted probability of detection curves: New statistical tools and progressive methodology. Journal of Nondestructive Evaluation, 36(1), 8</figcaption><p></p>
</figure>
</div>
<p>The image above illustrates the linear correlation between an independent variable and the mean of the dependent variable, as well as the inherent uncertainty in the statistical model. Specifically, the standard linear regression model assumes that this uncertainty follows a Gaussian (or Normal) distribution. Although the linear model predicts the variable’s average, we postulate that the true values of the dependent variable are randomly distributed around the mean, with the randomness described by the normal distribution.</p>
</section>
<section id="components-of-a-statistical-model" class="level2">
<h2 class="anchored" data-anchor-id="components-of-a-statistical-model">Components of a statistical model</h2>
<p>Gary King, professor at Harvard University and director of the Institute for Quantitative Social Science, explains clearly the main components of any statistical model in Chapter 1 of his book <a href="https://www.press.umich.edu/2153576/unifying_political_methodology">Unifying Political Methodology. The Likelihood Theory of Statistical Inference</a>. Here is what he explains.</p>
<ul>
<li><p><strong>Social system</strong>: this is the largest component of interest of social scientists. Social scientists, in a way or another, study social systems. They might be a neighborhood, a community, an election, or anything else. A social system includes features that are either known or estimable, and other important elements that remain unobserved and unobservable.</p></li>
<li><p><strong>Explanatory variables</strong>: also called independent variables, are measures of the features of a social systems. They are symbolized as <span class="math inline">\(X\)</span>, where <span class="math inline">\(X\)</span> contains measures of each of these features for all <span class="math inline">\(n\)</span> observations.</p></li>
<li><p><strong>Output</strong>: also dependent variable, is the output generated by the social system, and a consequence of the social system that can be observed and measured. For example, an election produces a victorious candidate, or a a mixture of certain political and cultural attitudes can generate more or less support for the government.</p>
<ul>
<li>When parts of the social system are under control of the researcher, the process of producing output is called an <strong><em>experiment</em></strong>. True experiments are only infrequently possible in the social sciences, but in statistics this term has also another meaning, and can be used where an experiment could be conducted, if only in theory. For example, a political election cannot be controlled by the researcher, but one can imagine the same election being “run” multiple times under the essentially identical conditions. Even under identical conditions, the social system outputs different results for each experiment. This is because output is produced in a <em>probabilistic</em> instead of deterministic manner.</li>
</ul></li>
<li><p><strong>Random variables</strong>: the output of a social system which is generated in a probabilistic manner, is a random variable (symbolized as <span class="math inline">\(Y\)</span>). Random variables are, operationally, the assignment of numbers to events (e.g.: Democratic President = 1, Republican President = 0; income = number of dollars, etc.), with a probability assigned to each number. Random variables are not really “random”, but follow specific probabilistic rules (i.e., they follow a particular statistical distribution, for example, a Normal distribution). Hence, although different outputs can be generated when running the same experiment under the same identical conditions, different output have different probabilities to be generated by the social system.</p></li>
<li><p><strong>The data</strong>: we don’t observe the random variable, but the data (which are generally symbolized as <span class="math inline">\(y\)</span>) , which are <span class="math inline">\(n\)</span> realizations of the random variable <span class="math inline">\(Y\)</span>. The data are a set of numbers that is assumed to be randomly drawn from the random variable <span class="math inline">\(Y\)</span> through a procedure called <em>sampling</em>. A data set is also called “the sample”.</p></li>
<li><p><strong>Statistical model</strong>: finally, a statistical model is a formal representation fo the process by which a social system produces output. The general goal of the model is to learn about the underlying process that generates output and hence the observed data. Statistical models are assumed to have both <em>systematic</em> and <em>stochastic</em> components. In the linear model below, for example, the stochastic component is represented as <span class="math inline">\(\epsilon\)</span>, and the systematic part is represented as <span class="math inline">\(bX_j\)</span>.</p>
<p><span class="math display">\[Y_j = i + bX_j + \epsilon_j\]</span></p>
<p>The stochastic component is also called the error term, and in a linear model is assumed to follow a normal probability distribution: <span class="math inline">\(\epsilon_j \sim f_n(e_j|0,\sigma^2)\)</span>.</p>
<p>An equivalent and more general way to express this statistical model is as follows:</p></li>
</ul>
<p><span class="math display">\[
Y_j \sim f_n(y_j|\mu_j, \sigma^2)\\
\mu_j = x_j\beta
\]</span></p>
<p>This expression more clearly shows that the output of the social system, the dependent variable <span class="math inline">\(Y\)</span> is a random variable, which in this case follows a normal probability distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma^2\)</span>, and where the mean <span class="math inline">\(\mu\)</span> varies across observations based on the values of the independent variables <span class="math inline">\(X\)</span>. In statistical terms, the mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma^2\)</span> are the <em>parameters</em> of the normal distribution.</p>
<p>Although in this course we focus only on linear model, the above expression can be further generalized to cover almost any other model, by written the two equations as follows:</p>
<p><span class="math display">\[
Y \sim f(y|\theta,\alpha)\\
\theta = g(X,\beta)
\]</span></p>
<p>The first equation represents the <em>stochastic</em> component, and is read “<span class="math inline">\(Y\)</span> is distributed as a function <span class="math inline">\(f\)</span> of the data <span class="math inline">\(y\)</span> given the parameter <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\alpha\)</span>”. Here, <span class="math inline">\(f\)</span> is a probability distribution, which is an explicit model of the form of uncertainty in the random variable <span class="math inline">\(Y\)</span> across repeated “experiments” (see above), and <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\alpha\)</span> are parameter vectors which can be predicted by using other variables.</p>
<p>The second equation represents the <em>systematic</em> component. Here, <span class="math inline">\(g\)</span> is a functional form, i.e., a precise statement of <em>how</em> a particular characteristics (<span class="math inline">\(\theta\)</span>) of the random dependent variable (<span class="math inline">\(Y\)</span>) is generated by certain features of the social system (the independent variables <span class="math inline">\(X\)</span>). In the linear model case, the functional form <span class="math inline">\(g\)</span> is linear. The vector of elements <span class="math inline">\(\beta\)</span> is called the effect parameters, representing the degree and direction of dependence of <span class="math inline">\(\theta\)</span> on the explanatory variables $X$. They are the so-called “coefficients” that we find when we fit a linear regression model. The interpretation of the effect parameters depends on the functional form that links the independent variables <span class="math inline">\(X\)</span> to the parameter of the independent variable $Y$. The systematic component of the statistical model is a statement of how different known features of the social system (the explanatory variables <span class="math inline">\(X\)</span>) generate various characteristics of the social system.</p>
</section>
</section>
<section id="linear-models" class="level1">
<h1>Linear models</h1>
<p>A linear model is a special kind of statistical model based on linear relationships (see the Pearson’s correlation coefficient) between two or more variables.</p>
<p>It is represented as a mathematical equation that links one (in case of a <em>simple</em> linear regression model) or more input variables (in case of a <em>multiple</em> linear regression model) to an output variable Y, by exploiting information contained in the <strong>association</strong> between the <strong>inputs</strong> and the <strong>output</strong>.</p>
<ul>
<li>The input variables are also called “predictors”, or “independent”, “explanatory”, or “antecedent” variables.</li>
<li>The output variable is also called “outcome”, “dependent”, or “consequent” variable.</li>
</ul>
<p>Linear regression models, as a basic application, can be used for answering questions of the <strong>“whether”</strong> or <strong>“if”</strong> variety. These questions ask whether two variables are correlated, causally or otherwise (<em>explanation</em>), or if something is more or less likely to happen in one set of circumstances or conditions than another (<em>prediction</em>).</p>
<ul>
<li><strong>Prediction</strong>: predict values taken by the dependent variable when we only know the values taken on by the independent variable(s) (e.g., predict income based on sex and level of education);</li>
<li><strong>Explanation</strong>: explaining the structure of a phenomenon by testing hypotheses about the relationships between dependent and independent variables (i.e., is there a relationships between two variables? How strong is it?)</li>
</ul>
<p>To do that, regression analysis computes an equation such that, given the input variables, the result of the equation yields:</p>
<ul>
<li>An estimate of the dependent variable (<em>prediction</em>).</li>
<li>A measure of the importance and <em>statistical significance</em> of the relationships between the independent variables and the dependent variable (<em>explanation</em>).</li>
</ul>
</section>
<section id="the-equation-form" class="level1">
<h1>The equation form</h1>
<p>The <strong>simple linear regression model</strong> is the simplest form of a linear regression model, in that it contains only a single independent variable (<span class="math inline">\(X\)</span>). The general form of the equation is the following:</p>
<p><span class="math display">\[Y_j = i + bX_j + e_j\]</span></p>
<p>For example, <span class="math inline">\(Y\)</span> could be income, and <span class="math inline">\(X\)</span> could be a variable used to try to explain/predict it, say level of education.</p>
<p>The <strong>multiple linear regression model</strong> is an extension of this simpler model, which includes more than one independent variable. For example, it may be used to predict income based on level of education, sex, and other variables.</p>
<p><span class="math display">\[Y_j = i + b_1X_{1j} + b_2X_{2j} + ... + e_j\]</span></p>
<p>From a data set containing the values of the <span class="math inline">\(Xs\)</span> and <span class="math inline">\(Y\)</span> variables, linear regression modeling finds the weights <span class="math inline">\(b_1\)</span>, <span class="math inline">\(b_2\)</span> (referred to as regression <strong>coefficients</strong>) that, multiplied by the values of the variable, represents the best approximation of the values of <span class="math inline">\(Y\)</span> in the equation. To estimate the coefficients of the model, the most common procedure is referred to as <strong>ordinary least squares (OLS)</strong> criterion.</p>
</section>
<section id="multiple-linear-regression-model" class="level1">
<h1>Multiple linear regression model</h1>
<p>In practice, the single linear regression model is never used. If you are only interested in the relationship between two variables, you can calculate a correlation coefficient.</p>
<p>However, the problem with the correlation coefficient is that the relationships between two variables is always ambiguous, and <strong>alternative explanations</strong> abound. For example, the correlation between income and education can simply reflect a difference in the status of the family of origin. Wealthier families have more resources and connections, send their sons and daughters to a better school and help them find better jobs, resulting in higher incomes.</p>
<p>In general terms, what makes the association between two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> ambiguous, leading to alternative explanations, is that <em>people who differ on X and Y also likely differ on many other things, and it may be those things that are responsible for the association.</em></p>
<p>Multiple regression gives a researcher a means of engaging in a kind of mathematically aided counter-factual reasoning by estimating what the association between each independent variable X and the dependent variable Y would be <em>if people did not differ on the other independent variables</em> in the regression model. It does this by “mathematically equating” people (or whatever the unit of analysis is) on those variables. This equating process is also referred to as <em>partialling out</em> those other variables from the association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, or <em>statistically control</em> of those variables.</p>
<blockquote class="blockquote">
<p>Partial out: “to give (a variable) a fixed value while considering the relationship between two related variables”</p>
</blockquote>
<p>For example, to estimate the effect of level of education on income, we could fit a multiple linear regression model. This model would include variables that we think are associated with income. For example, level of education, wealth of the family of origin, and a measure of social connection. This model can estimate the effect of education on income, <em>holding constant all other independent variables</em> (i.e., net of the effect of other variables). In practical terms, this means that the regression model shows an estimate of the effect of education on income among individuals with families of the same status and with the same type of social connections, so this variable should no longer have a confounding effect on our estimate of the effect of education.</p>
</section>
<section id="elements-of-the-linear-model-equation" class="level1">
<h1>Elements of the linear model equation</h1>
<p>To present the main elements of a linear regression model, let’s consider its simplest form:</p>
<p><span class="math display">\[Y_j = i + bX_j + e_j\]</span></p>
<section id="the-index-j" class="level2">
<h2 class="anchored" data-anchor-id="the-index-j">The index j</h2>
<p>The index <span class="math inline">\(_j\)</span> indicates any unique observation/case within the data set. Since rows represent cases, you can view the subscript <span class="math inline">\(_j\)</span> as a row in a data set.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  j  Y  X
1 1 12 10
2 2 23 35
3 3 34 45
4 4 54 57
5 5 45 87</code></pre>
</div>
</div>
<p>The index may also be omitted and the regression equation represented as <span class="math inline">\(Y = i + bX + e\)</span>, but it makes it explicit that, for each case, the equation establishes a relationships between the values of the variable <span class="math inline">\(Y\)</span> (the dependent or outcome variable) and <span class="math inline">\(X\)</span> (the independent or antecedent variable).</p>
</section>
<section id="intercept" class="level2">
<h2 class="anchored" data-anchor-id="intercept">Intercept</h2>
<p><span class="math display">\[Y_j = i + bX_j + e_j\]</span></p>
<p>The <span class="math inline">\(i\)</span> indicates a numerical coefficient estimated by the regression model. It is a constant (i.e., a fixed value) and is referred to as <em>intercept</em> or <em>constant</em>. It is the average (mean) value of <span class="math inline">\(Y\)</span> when the independent variable(s) assume the value 0.</p>
<p>Although the intercept is mathematically significant, <em>sometimes</em> <em>it makes no sense and cannot be interpreted.</em> It is not meaningful when:</p>
<ul>
<li>The independent variables do not include zero in their data range;</li>
<li>This value is not significant or even impossible.</li>
</ul>
<p>For example, if we predict the weight of people based on their height, the intercept has no substantial meaning, because there is no person with a height equal to zero.</p>
</section>
<section id="regression-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="regression-coefficient">Regression coefficient</h2>
<p><span class="math display">\[Y_j = i + bX_j + e_j\]</span></p>
<p>The letter <span class="math inline">\(b\)</span> (or <em>beta</em>) indicates a numerical coefficient estimated by the regression model (e.g., through the OLS procedure). It is referred to as regression <em>coefficient</em> and represents the <em>weight</em> assigned to the values of the variable <span class="math inline">\(X\)</span>.</p>
<p>In the simple linear model, it represents <em>the average change in</em> <span class="math inline">\(Y\)</span> <em>for every one unit</em> <em>increase in</em> <span class="math inline">\(X\)</span>. In the multiple linear regression model it represents the average change in <span class="math inline">\(Y\)</span> for every one unit increase in <span class="math inline">\(X\)</span>, <em>holding all other independent variables constant.</em> For this reasons, these coefficients represent measures of <strong>partial association</strong> (i.e., each coefficient represents the part of association that is specific to a particular variable).</p>
</section>
<section id="error" class="level2">
<h2 class="anchored" data-anchor-id="error">Error</h2>
<p>The letter <span class="math inline">\(e\)</span> indicates the <em>error</em> <em>term</em> or <em>residual</em>, and represents the imprecision and uncertainty in the estimate. It is the difference between the values of <span class="math inline">\(Y\)</span> estimated by the model, and the true values of <span class="math inline">\(Y\)</span>.</p>
</section>
</section>
<section id="fit-a-linear-regression-model-with-r" class="level1">
<h1>Fit a linear regression model with R</h1>
<p>The R function to fit a linear regression model is <code>lm</code>.</p>
<p>The function takes at least two arguments separated by a <em>tilde</em> (the symbol <code>~</code> : check online how to write that with your specific keyword. You can also copy/paste it from the help by typing <code>?tilde</code>):</p>
<ul>
<li>To the left of the tilde is the dependent variable (<span class="math inline">\(Y\)</span>)</li>
<li>To the right of the tilde is the independent variables (<span class="math inline">\(X\)</span>) separated with the plus (<code>+</code>) symbol.</li>
</ul>
<p>The argument <code>data</code> is used for the name of the data set, which is usually a data frame.</p>
<p>The function <code>summary</code> is used to see the results of the model fitting functions.</p>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>Load the data set <code>glbwarm</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data set</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>glbwarm <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/glbwarm.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="simple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="simple-linear-regression">Simple linear regression</h3>
<p>Let’s fit a simple linear regression model that predicts support for government action to mitigate climate change (independent variable <span class="math inline">\(Y = govact\)</span>), based on negative emotion about this issue (<span class="math inline">\(X = negemot\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(govact <span class="sc">~</span> negemot, <span class="at">data =</span> glbwarm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code>summary</code> produces the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot, data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3285 -0.6731  0.1018  0.7554  3.2142 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.75732    0.09866   27.95   &lt;2e-16 ***
negemot      0.51424    0.02548   20.18   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.111 on 813 degrees of freedom
Multiple R-squared:  0.3338,    Adjusted R-squared:  0.333 
F-statistic: 407.3 on 1 and 813 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="multiple-linear-regression">Multiple linear regression</h3>
<p>The following piece of code fits a multiple linear regression model that predicts support for government action to mitigate climate change (independent variable <span class="math inline">\(Y = govact\)</span>), based on several variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(govact <span class="sc">~</span> negemot <span class="sc">+</span> posemot <span class="sc">+</span> ideology <span class="sc">+</span> sex <span class="sc">+</span> age, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> glbwarm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age, 
    data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8381 -0.6834  0.0705  0.7008  3.4266 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.063607   0.205323  19.791  &lt; 2e-16 ***
negemot      0.440781   0.026433  16.676  &lt; 2e-16 ***
posemot     -0.026778   0.028145  -0.951    0.342    
ideology    -0.218269   0.027043  -8.071 2.51e-15 ***
sex         -0.010066   0.076743  -0.131    0.896    
age         -0.001309   0.002371  -0.552    0.581    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.067 on 809 degrees of freedom
Multiple R-squared:  0.3883,    Adjusted R-squared:  0.3845 
F-statistic: 102.7 on 5 and 809 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-the-output" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-the-output">Interpretation of the output</h3>
<p>Consider the output of the <code>lm2</code> multiple linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age, 
    data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8381 -0.6834  0.0705  0.7008  3.4266 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.063607   0.205323  19.791  &lt; 2e-16 ***
negemot      0.440781   0.026433  16.676  &lt; 2e-16 ***
posemot     -0.026778   0.028145  -0.951    0.342    
ideology    -0.218269   0.027043  -8.071 2.51e-15 ***
sex         -0.010066   0.076743  -0.131    0.896    
age         -0.001309   0.002371  -0.552    0.581    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.067 on 809 degrees of freedom
Multiple R-squared:  0.3883,    Adjusted R-squared:  0.3845 
F-statistic: 102.7 on 5 and 809 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This output is composed of the several sections.</p>
<section id="residuals" class="level4">
<h4 class="anchored" data-anchor-id="residuals">Residuals</h4>
<p>At the top of the output, there is the five-number summary of residuals (the errors). In linear regression, the distribution is expected to have some characteristics, such as to be normally distributed and homoskedastik. These characteristics will be discussed later when presenting the linear regression assumptions.</p>
</section>
<section id="residual-standard-error" class="level4">
<h4 class="anchored" data-anchor-id="residual-standard-error"><strong>Residual standard Error</strong></h4>
<p>Before interpreting the results (the coefficients), you want to determine how well the model fits the data. Does it do a good job of explaining changes in the dependent variable? At the bottom of the table, there is general information to evaluate the “goodness-of-fit” of the model:</p>
<p>Residual standard error (or RSE) is the standard deviation of the residuals. It is a measure of the variability or dispersion of the observed data points around the fitted regression line in a linear regression model. The lower the value for RSE, the more closely a model is able to fit the data. It is calculated as the square root of the residual sum of squares (i.e., the differences between the predicted and observed values: <span class="math inline">\(RSS = \Sigma_{j=1}^{n}(\hat y_j-y_j)\)</span>) divided by the degrees of freedom (<span class="math inline">\(n-p-1\)</span>), where <span class="math inline">\(n\)</span> is the number of observations in the data set, and <span class="math inline">\(p\)</span> is the number of predictors (independent variables) in the model.</p>
<p>In simpler terms, RSE tells you how much the observed data points deviate from the fitted regression line on average. In this case, the average deviation is 1.067 points. The RSE values are expressed in the same units as the dependent variable. In this case, the dependent variable is <span class="math inline">\(govact\)</span> which is measured on a scale from 1 to 7.</p>
<p>In general terms, a smaller RSE indicates that the data points are closer to the fitted line and the model is a better fit for the data. Conversely, a larger RSE indicates that the data points are more spread out and the model may not be a good fit for the data.</p>
</section>
<section id="r-squared" class="level4">
<h4 class="anchored" data-anchor-id="r-squared"><strong>R-squared</strong></h4>
<p>The most used index of goodness-of-fit is the <em>R-squared</em> (or <span class="math inline">\(R^2\)</span>). It indicates on a scale from 0 to 1 the extent to which the model can explains/predicts the dependent variable. It is calculated as the ratio of the residual sum of squares (i.e., the differences between the observed values and the predicted values: <span class="math inline">\(RSS = \Sigma_{j=1}^{n}(\hat y_j-y_j)\)</span>) to the total variation (total sum of squares, i.e., the difference between the observed values and the mean of the variable: <span class="math inline">\(TSS = \Sigma_{j=1}^{n}(y_j-\bar y)\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>RSS <span class="ot">&lt;-</span> <span class="fu">sum</span>( (lm2<span class="sc">$</span>fitted.values <span class="sc">-</span> lm2<span class="sc">$</span>model<span class="sc">$</span>govact)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>TSS <span class="ot">&lt;-</span> <span class="fu">sum</span>( (lm2<span class="sc">$</span>model<span class="sc">$</span>govact <span class="sc">-</span> <span class="fu">mean</span>(lm2<span class="sc">$</span>model<span class="sc">$</span>govact))<span class="sc">^</span><span class="dv">2</span> ) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> (RSS<span class="sc">/</span>TSS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3883189</code></pre>
</div>
</div>
<p>Considering the formula, it should be clear that <span class="math inline">\(R^2\)</span> is the standardized residual standard error of the regression (RSE). It is generally interpreted as the proportion of variance (of the dependent variable) explained by the model. <em>Adjusted R-squared</em> adds a penalty based on the complexity of the model (number of variables) and can be preferred when fitting multiple linear regression models. Both the Multiple R-squared and the Adjusted R-squared values can be reported. This value can be reported as a percentage of the explained variance. For example, in this case, the model explains about 38% of the variance.</p>
<p>The <span class="math inline">\(R\)</span> in <span class="math inline">\(R^2\)</span> might remind you the Pearson correlation coefficient <span class="math inline">\(r\)</span>. Indeed, in the simple linear regression model, <span class="math inline">\(R^2\)</span> is just the square of the Pearson correlation coefficient.</p>
<p>Gary King (<a href="https://www.press.umich.edu/2153576/unifying_political_methodology">1998</a>) also notices that <span class="math inline">\(R^2\)</span> is a relative measure that can be used to compare different models used to predict the same dependent variable:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(R^2\)</span> is typically understood as the percentage of variance in <span class="math inline">\(y\)</span> (n.r.: <span class="math inline">\(y\)</span> is the observed variable) explained by the systematic component. But some of the variation in <span class="math inline">\(y\)</span> is systematic and some results from the random variation across experiments as governed by the stochastic component. Intuitively, one wants <span class="math inline">\(R^2\)</span> to measure only the proportion of systematic variation explained. To explain too little of the systematic part or too much of the random part are equally undesirable alternatives. Unfortunately, whether 58%, 5%, or 99% is all, less than all, or an over-fitting of the systematic component is not knowable in the context of one regression. The concept of an <span class="math inline">\(R^2\)</span> that is “good” in an absolute way is nonsensical. Hence, like likelihood, <span class="math inline">\(R^2\)</span> and other goodness-of-fit statistics are relative measures only (<a href="https://www.press.umich.edu/2153576/unifying_political_methodology">King, G. (1998), p.&nbsp;24, footnote 7</a>).</p>
</blockquote>
</section>
<section id="f-statistic-and-p-value" class="level4">
<h4 class="anchored" data-anchor-id="f-statistic-and-p-value"><strong>F-statistic and p-value</strong></h4>
<p>The last row of the output reports the <em>F-statistic</em> and the <em>p-value</em> of the model. We already said that linear regression modeling attempts to identify variables that help explain/predict another variable better than its own average (mean). The <em>F-statistic</em> compares the fitted linear model with a model that only uses the mean of the dependent variable. If the p-value is below 0.05, the fitted model is significantly better that a model that uses only the mean.</p>
<p>The calculation of the F-statistic employs the same mathematical and statistical elements already discussed:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>TSS <span class="ot">&lt;-</span> <span class="fu">sum</span>( (glbwarm<span class="sc">$</span>govact <span class="sc">-</span> <span class="fu">mean</span>(glbwarm<span class="sc">$</span>govact))<span class="sc">^</span><span class="dv">2</span> ) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>RSS <span class="ot">&lt;-</span> <span class="fu">sum</span>( (lm2<span class="sc">$</span>fitted.values <span class="sc">-</span> glbwarm<span class="sc">$</span>govact)<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="co"># number of independent variables we are testing</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(glbwarm<span class="sc">$</span>govact) <span class="co"># total number of observations</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>F_statistic <span class="ot">&lt;-</span> ( (TSS<span class="sc">-</span>RSS)<span class="sc">/</span>p ) <span class="sc">/</span> (RSS<span class="sc">/</span>(n<span class="sc">-</span>p<span class="dv">-1</span>))</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>F_statistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 102.7169</code></pre>
</div>
</div>
<p>The <em>p-value</em> associated with the F-statistic is the probability of obtaining a value as extreme or more extreme than the observed F-statistic, assuming that the null hypothesis is true. A small p-value (usually less than 0.05) indicates strong evidence against the null hypothesis and suggests that the regression model is a good fit to the data.</p>
<blockquote class="blockquote">
<p>Note: The p-value is expressed in scientific notation (e.g., 2.2e-16). To convert it to a common number, you can use the function <code>format</code>, adding the number you want to convert, and the option <code>scientific=FALSE</code>. For example:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span>(<span class="fl">2.2e-16</span>, <span class="at">scientific=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.00000000000000022"</code></pre>
</div>
</div>
</section>
<section id="coefficients" class="level4">
<h4 class="anchored" data-anchor-id="coefficients"><strong>Coefficients</strong></h4>
<p>The coefficient table includes the following information:</p>
<ul>
<li><p><strong>Estimate</strong>: the regression coefficients of the model (i.e., the <span class="math inline">\(b\)</span> (beta) “weight” of the independent variables).</p></li>
<li><p><strong>Std. Error</strong>: the standard error of the estimates (coefficients), i.e., their standard deviations. We know that standard deviation is a measure of spread and precision with which the regression coefficient is measured.</p></li>
<li><p><strong>t value</strong>: this is the <em>t-statistic</em> and measures the significance of each coefficient. It is calculated as the ratio of the coefficient to its standard error. It’s used to calculate the p-value (<span class="math inline">\(Pr (&gt;|t|)\)</span>). Statistically significant p-values are those lower than 0.05 and are marked with one or more asterisks. They indicate that the independent variable has a statistically significant relationship with the dependent variable. In other words, we can conclude that, if all model assumptions held, there is an association between the variables, since it would be unlikely (less than 5% chance if <span class="math inline">\(p &lt; 0.05\)</span>) to observe similar values if such an association did not exist.</p></li>
</ul>
<blockquote class="blockquote">
<p>Notice that the analysis is assumed to be carried out on a <em>representative sample</em> to draw conclusions on a <em>population</em>. A sample is a subset of cases (e.g., the 815 Americans in the <code>glbwarm</code> data set) collected from a larger population (e.g., the entire American population). The sample represents the population on a small scale. A “statistically significant” relationship indicates that, under the statistical model, the observed relationship is likely true and not an artifact in the data sample we analyzed. It suggests that the relationship exists both in the observed data (a sample) and in the population from which the data originated.</p>
</blockquote>
</section>
</section>
</section>
</section>
<section id="interpretation" class="level1">
<h1>Interpretation</h1>
<p>This is how we can interpret the output of the <code>lm2</code> multiple linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age, 
    data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8381 -0.6834  0.0705  0.7008  3.4266 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.063607   0.205323  19.791  &lt; 2e-16 ***
negemot      0.440781   0.026433  16.676  &lt; 2e-16 ***
posemot     -0.026778   0.028145  -0.951    0.342    
ideology    -0.218269   0.027043  -8.071 2.51e-15 ***
sex         -0.010066   0.076743  -0.131    0.896    
age         -0.001309   0.002371  -0.552    0.581    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.067 on 809 degrees of freedom
Multiple R-squared:  0.3883,    Adjusted R-squared:  0.3845 
F-statistic: 102.7 on 5 and 809 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="goodness-of-fit" class="level2">
<h2 class="anchored" data-anchor-id="goodness-of-fit"><strong>Goodness-of-fit</strong></h2>
<p>The model explains a statistically significant (p &lt; .001) and substantial proportion of variance (Multiple R-squared: 0.3883, Adjusted R-squared: 0.3845).</p>
</section>
<section id="estimates" class="level2">
<h2 class="anchored" data-anchor-id="estimates"><strong>Estimates</strong></h2>
<section id="intercept-1" class="level3">
<h3 class="anchored" data-anchor-id="intercept-1"><strong>Intercept</strong></h3>
<p>The intercept term in a linear regression model represents the value of the dependent variable when all the independent variables in the model are equal to zero. The intercept is not always meaningful. You need to consider the distribution of your variables (e.g., using the five-number summary). For example, zero does not even exist in the distribution of <code>negemot</code> and <code>ideology</code>. Therefore, the intercept is not meaningful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glbwarm<span class="sc">$</span>negemot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   2.330   3.670   3.558   5.000   6.000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glbwarm<span class="sc">$</span>ideology)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   3.000   4.000   4.083   5.000   7.000 </code></pre>
</div>
</div>
</section>
<section id="coefficients-1" class="level3">
<h3 class="anchored" data-anchor-id="coefficients-1"><strong>Coefficients</strong></h3>
<p>Take into consideration the statistical significance of the variables. Only two variables are statistically significant: <code>negemot</code> and <code>ideology</code>. They are significant at p &lt; 0.001 (three asterisks). This means that there is a 1 in 1000 chance of observing such values in a sample, if there was no real relationship between the variables in the population. The other variables are not statistically significant. This means that we cannot conclude that these independent variables are correlated to the dependent variable.</p>
<p>The coefficients of a multiple regression model are <em>measures of partial association</em> that quantify the component of the association between an independent and a dependent variable that is unique to that independent variable, relative to other independent variables in the model.</p>
<section id="continuous-or-discrete-variables" class="level4">
<h4 class="anchored" data-anchor-id="continuous-or-discrete-variables">Continuous or discrete variables</h4>
<p>When we have continuous or discrete variables (e.g.: negative emotion and ideology), we can read the coefficients as follows:</p>
<ul>
<li><p>Holding all other variables constant (or, “all other variables being equal”, or a similar formulation), two cases that differ by one unit on the negative emotion scale, are estimated to differ by 0.44 unit on average in their support for government action to mitigate climate change. Or also: a one-unit increase on the negative emotion scale (<code>negemot</code>) would result in a 0.44 increase in support for government action to mitigate climate change.</p></li>
<li><p>Holding all other variables constant, two cases that differ by one unit on the ideology scale, are estimated to differ by -0.22 unit in their support for government action to mitigate climate change, with cases one unit higher on that scale (i.e., republicans) estimated to be -0.22 unit lower in their support for government action. Or also, a one-unit increase in the ideology variable would result in a 0.22 <em>decrease</em> (notice the negative sign: -0.218269) in support for government action to mitigate climate change.</p></li>
</ul>
</section>
<section id="dichotomous-variables" class="level4">
<h4 class="anchored" data-anchor-id="dichotomous-variables"><strong>Dichotomous variables</strong></h4>
<p>A dichotomous variable is also a variable that takes on only two possible values. Examples of dichotomous variables include variables like gender (male/female), yes/no questions, and success/failure outcomes. The two values they take are usually represented by 0 and 1.</p>
<p>The variable <code>sex</code> in the <code>glbwarm</code> data set is a dichotomous variable where 0 represents females and 1 represents males. A unit change corresponds to switching from one category (0) to the other (1).</p>
<p>The coefficient for <code>sex</code> (<span class="math inline">\(-0.010066\)</span>) indicates that, on average, males (1) are less supportive of government action by 0.01 units compared to females (0). However, this difference is not statistically significant, and thus, there is no evidence of systematic gender differences in support for government action.</p>
<p>Note that to interpret a dichotomous variable of this kind, it is necessary to know what value 0 and value 1 correspond to. Also note that the lowest value (0) is used as the <em>reference category</em>. Therefore, the coefficient of a dichotomous variable expresses the difference, on average, in the value of the dependent variable between category 0 (in this case females) and 1 (in this case males).</p>
</section>
<section id="multicategorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="multicategorical-variables">Multicategorical variables</h4>
<p>Multicategorical variables are expressed using <em>dummy variables</em>. Notice that a <em>dummy variable</em> is a specific type of dichotomous variable, but the two are not synonymous. The term “dichotomous variable” refers to variables with only two states, such as “male” or “female”. It is one of several types of variables, including “continuous variables”, “discrete variables”, and “ordinal variables”.</p>
<p>On the other hand, a dummy variable represents the absence (0) or presence (1) of a particular characteristic and is often used to transform multicategorical variables. This process, called “dummy coding”, involves creating a new variable that takes on a value of 1 if the original variable belongs to a certain category and 0 otherwise. For example, if the original variable was “color” with levels “red,” “green,” and “blue,” three dummy variables could be created to represent each color: “red” (1 if red, 0 otherwise), “green” (1 if green, 0 otherwise), and “blue” (1 if blue, 0 otherwise). Therefore, dummy variables often appear as a set of variables that allows us to specify categorical explanatory variables as independent variables in statistical analyses.</p>
<p>Since there are no multicategorical variables in the <code>glbwarm</code> data set, we create one by grouping the age variable into age classes. We create this categorical variable as a <code>factor</code>, used for this type of variable. Note that in the last line, we specify the <code>levels</code> of the categorical variable, which are the categories included in the categorical variable. The first level is always the <em>reference category</em> in the regression analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(tidyverse)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>glbwarm <span class="ot">&lt;-</span> glbwarm <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create categories</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_group =</span> dplyr<span class="sc">::</span><span class="fu">case_when</span>(</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&gt;=</span> <span class="dv">17</span> <span class="sc">&amp;</span> age <span class="sc">&lt;=</span> <span class="dv">34</span> <span class="sc">~</span> <span class="st">"17-34"</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&gt;=</span> <span class="dv">35</span> <span class="sc">&amp;</span> age <span class="sc">&lt;=</span> <span class="dv">54</span> <span class="sc">~</span> <span class="st">"35-54"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&gt;=</span> <span class="dv">55</span>             <span class="sc">~</span> <span class="st">"55+"</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert to factor</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_group =</span> <span class="fu">factor</span>(</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>      age_group,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">level =</span> <span class="fu">c</span>(<span class="st">"17-34"</span>,<span class="st">"35-54"</span>, <span class="st">"55+"</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(glbwarm<span class="sc">$</span>age_group), <span class="at">main =</span> <span class="st">"Age Groups"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can double check the levels of the variable by using the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(glbwarm<span class="sc">$</span>age_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "17-34" "35-54" "55+"  </code></pre>
</div>
</div>
<p>We use this variable in a new regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lm3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(govact <span class="sc">~</span> negemot <span class="sc">+</span> posemot <span class="sc">+</span> ideology <span class="sc">+</span> sex <span class="sc">+</span> age_group, </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> glbwarm)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age_group, 
    data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8196 -0.6738  0.0680  0.7013  3.4455 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     4.014414   0.194228  20.669  &lt; 2e-16 ***
negemot         0.440742   0.026446  16.666  &lt; 2e-16 ***
posemot        -0.026907   0.028148  -0.956    0.339    
ideology       -0.219078   0.026970  -8.123  1.7e-15 ***
sex            -0.005455   0.077968  -0.070    0.944    
age_group35-54  0.015133   0.102199   0.148    0.882    
age_group55+   -0.044887   0.097945  -0.458    0.647    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.068 on 808 degrees of freedom
Multiple R-squared:  0.3885,    Adjusted R-squared:  0.3839 
F-statistic: 85.54 on 6 and 808 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The variable has three levels, but as can be observed, the output reports only two levels. The omitted level is the reference category. As with the dichotomous variable <code>sex</code> where the reference category is 0 (female), in this case the reference category is the age class <code>17-34</code>.</p>
<p>Similarly to the dichotomous variable case, the coefficients indicate the difference between the category indicated in the table and the reference category. For example, holding all other variables constant, individuals aged between 35 and 54 have, on average, a 0.015133 higher value on the dependent variable <code>govact</code> (not statistically significant).</p>
<p>We can also change the reference category with the command <code>relevel</code>. For instance, we can use older people as reference. The interpretation changes accordingly. For example, individuals aged between 17 and 34 have, on average, a 0.044887 higher value on the dependent variable <code>govact</code> (not statistically significant).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>glbwarm<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="fu">relevel</span>(glbwarm<span class="sc">$</span>age_group, <span class="at">ref =</span> <span class="st">"55+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>lm3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(govact <span class="sc">~</span> negemot <span class="sc">+</span> posemot <span class="sc">+</span> ideology <span class="sc">+</span> sex <span class="sc">+</span> age_group, </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> glbwarm)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age_group, 
    data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8196 -0.6738  0.0680  0.7013  3.4455 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     3.969526   0.199454  19.902  &lt; 2e-16 ***
negemot         0.440742   0.026446  16.666  &lt; 2e-16 ***
posemot        -0.026907   0.028148  -0.956    0.339    
ideology       -0.219078   0.026970  -8.123  1.7e-15 ***
sex            -0.005455   0.077968  -0.070    0.944    
age_group17-34  0.044887   0.097945   0.458    0.647    
age_group35-54  0.060020   0.088591   0.677    0.498    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.068 on 808 degrees of freedom
Multiple R-squared:  0.3885,    Adjusted R-squared:  0.3839 
F-statistic: 85.54 on 6 and 808 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>What <code>R</code> does in the background is transform the multicategorical variable into a set of dummy variables. In this case, each dummy variable represents a specific age group and takes a value of <code>1</code> if the individual falls within that age group and <code>0</code> otherwise. Notice that to represent a variable composed of <code>N</code> categories, <code>N-1</code> dummy variables are needed. For example, in this case, we have three age groups, so <code>N-1 = 2</code> dummy variables are needed. Indeed, it is not necessary to use a dummy variable for the last age group, as it is represented by all individuals who have a value of zero in the previous dummy variables.</p>
<p>Consider for example three individuals of different age groups. They are represented through dummy coding. As you can see, only two dummy variables are needed, as the last category corresponds to individuals who have a value of 0 in the other categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="st">"age17_34"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">"age35_54"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>           <span class="st">"age55+"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age17_34 age35_54 age55.
1        1        0      0
2        0        1      0
3        0        0      1</code></pre>
</div>
</div>
<p>Let’s create, for comparison, two dummy variables instead of a single factor variable as previously done, and run the same regression model to compare the results. As you can see, they are identical.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy coding</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>glbwarm<span class="sc">$</span>age_17_34 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glbwarm<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">17</span> <span class="sc">&amp;</span> glbwarm<span class="sc">$</span>age <span class="sc">&lt;=</span> <span class="dv">34</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>glbwarm<span class="sc">$</span>age_35_54 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glbwarm<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">35</span> <span class="sc">&amp;</span> glbwarm<span class="sc">$</span>age <span class="sc">&lt;=</span> <span class="dv">54</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># we omit the third class, as it is already represented by the zeros in </span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the first two dummy variables</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># glbwarm$age_55 &lt;-  ifelse(glbwarm$age &gt;= 55, 1, 0)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lm3c <span class="ot">&lt;-</span> <span class="fu">lm</span>(govact <span class="sc">~</span> negemot <span class="sc">+</span> posemot <span class="sc">+</span> ideology <span class="sc">+</span> sex <span class="sc">+</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>            age_17_34 <span class="sc">+</span> age_35_54, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> glbwarm)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm3c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = govact ~ negemot + posemot + ideology + sex + age_17_34 + 
    age_35_54, data = glbwarm)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8196 -0.6738  0.0680  0.7013  3.4455 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.969526   0.199454  19.902  &lt; 2e-16 ***
negemot      0.440742   0.026446  16.666  &lt; 2e-16 ***
posemot     -0.026907   0.028148  -0.956    0.339    
ideology    -0.219078   0.026970  -8.123  1.7e-15 ***
sex         -0.005455   0.077968  -0.070    0.944    
age_17_34    0.044887   0.097945   0.458    0.647    
age_35_54    0.060020   0.088591   0.677    0.498    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.068 on 808 degrees of freedom
Multiple R-squared:  0.3885,    Adjusted R-squared:  0.3839 
F-statistic: 85.54 on 6 and 808 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="residuals-and-assumptions" class="level1">
<h1>Residuals and assumptions</h1>
<p>The interpretation of residuals requires to discuss the assumptions of linear models. Linear regression is founded on some assumptions. The violation of these assumptions can have adverse effects on the interpretation of the model and on inference, therefore we should be mindful of the assumptions the regression model makes. The main assumptions of the linear regression model are the following:</p>
<ul>
<li><strong>Linearity</strong>: Linearity states that the relationships between the variables in the model are linear in nature, or at least approximately linear. For obvious reasons, it’s wrong to use a linear model to understand non-linear relations. Linearity is violated, for instance, when for low values of <span class="math inline">\(X\)</span>, a <em>one</em> unit increase in <span class="math inline">\(X\)</span> corresponds to an increase of <em>one</em> unit in <span class="math inline">\(Y\)</span>, but for high values of <span class="math inline">\(X\)</span>, <em>one</em> unit increase in <span class="math inline">\(X\)</span> corresponds to an increase of <em>three</em> units in <span class="math inline">\(Y\)</span>.</li>
<li><strong>Normality</strong>: The assumption of normality states that the errors (i.e.&nbsp;residuals) are normally distributed. In general, <em>linear regression is considered to be “robust” to mild violation of normality</em>. Research suggests that only the most severe violations of the normality assumption substantially affect the validity of statistical inferences from a regression analysis unless the sample size is quite small.</li>
<li><strong>Homoscedasticity</strong>: Homoskedasticity (also homoscedasticity) states that errors in estimation are almost equal across the range of the estimated values of the outcome <span class="math inline">\(\hat Y\)</span>. When this condition is not met, the errors in estimation are said to be <em>heteroscedastic</em>.</li>
<li><strong>Independence</strong>: The errors in estimation should be statistically independent. In the most basic terms, two things are independent if information about one gives no information about the other. A typical violation of independence is the autocorrelation in <em>time series data</em>, which has to be handled with specific time series techniques.</li>
<li><strong>Outliers</strong>: Observations particularly different from the average are called outliers. They may have excessive influence over the coefficient estimates (<em>“influential observations”</em>). If so, they must be thoroughly inspected.</li>
<li><strong>No multicollinearity</strong>: Multicollinearity is the occurrence of high correlation among two or more independent variables in a multiple regression model. It makes it difficult to distinguish the effect of the variables.</li>
</ul>
<section id="check-the-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="check-the-assumptions">Check the assumptions</h2>
<p>R can easily provide the analyst with four <em>diagnostic plots</em> you can use to assess the assumptions of the model.</p>
<p>You can visualize the plots by using the function <code>plot</code> applied to the “object” corresponding to your fitted model. You can visualize the plots together by using <code>par(mfrow=c(2,2))</code> before calling the <code>plot</code> function. In this way, you create a 2x2 layer to show the 4 main diagnostic plots on the same page. You can also visualize a single plot by using the number of the plot inside the <em>plot</em> function (e.g.: <code>plot(lm_object, 1)</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In general, you want the <em>Normal Q-Q plot</em> to show points along a <em>diagonal</em> line, and the other three plots showing <em>randomly scattered</em> points, without any evident systematic pattern.</p>
<p>Points showing a conic shape in the <em>Residuals vs Fitted</em> and <em>Scale-Location</em> plots are indicative of an <em>heteroskedasticity</em> problem (violation of the homoscedasticity assumption). Ideally, you should see a <em>roughly horizontal line</em> <em>with</em> <em>equally spread</em> <em>points</em>. A statistical test for checking homoscedasticity is the Breusch-Pagan test. It is included in the <code>lmtest</code> library. A p-value &lt; 0.05 suggests heteroskedasticity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.package</span>(<span class="st">"lmtest"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  lm2
BP = 14.787, df = 5, p-value = 0.01131</code></pre>
</div>
</div>
<p>Heteroskedasticity does not impact coefficients, but affects statistical tests (e.g., tests that conclude whether the coefficients are statistically significant). There are different ways to mitigate or resolve this and other assumption issues. A way is to correct the regression model with <em>Heteroscedasticity-Consistent Standard Errors</em>. In R you need the <code>lmtest</code> and <code>sandwich</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.package</span>(<span class="st">"sandwich"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(lm2, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(lm2, <span class="at">type =</span> <span class="st">"HC3"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

              Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)  4.0636065  0.1965257 20.6772 &lt; 2.2e-16 ***
negemot      0.4407807  0.0282082 15.6260 &lt; 2.2e-16 ***
posemot     -0.0267777  0.0317203 -0.8442    0.3988    
ideology    -0.2182689  0.0289974 -7.5272 1.384e-13 ***
sex         -0.0100662  0.0753805 -0.1335    0.8938    
age         -0.0013087  0.0022916 -0.5711    0.5681    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>You can also see that certain dots are marked by a number. These are points with unexpectedly high residuals (error) and you could inspect them to find out why (e.g., to exclude there are errors in the data set). Also check if any point in the <em>Residuals vs Leverage</em> plot falls outside of Cook’s distance (a red dashed lines). These points are considered to be <em>influential observations</em>. Influential points have a large influence on the model and should be carefully inspected. In this case there are no influential points, and the red dashed line is not even displayed.</p>
<p>To verify <em>multicollinearity</em> you can also calculate the <em>VIF (Variance Inflation Factor)</em>. The function to calculate it is <code>vif</code>, and is included in the package <code>car</code>. The smallest possible value of VIF is one (absence of multicollinearity), and as a rule of thumb, a VIF value that exceeds 5 or 10 indicates a problematic amount of collinearity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install the package</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"car"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> negemot  posemot ideology      sex      age 
1.166374 1.026410 1.194399 1.052894 1.071034 </code></pre>
</div>
</div>
</section>
</section>
<section id="reading-resources-exercises" class="level1">
<h1>Reading, resources, exercises</h1>
<section id="readings" class="level2">
<h2 class="anchored" data-anchor-id="readings">Readings</h2>
<ul>
<li>Hayes’ book, Chapter 2 - Regression fundamentals</li>
</ul>
</section>
<section id="resources" class="level2">
<h2 class="anchored" data-anchor-id="resources">Resources</h2>
<p>There are plenty of resources online about linear regression and R. For example:</p>
<ul>
<li><a href="http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/">This website</a> provides a clear explanation of regression diagnostic plots</li>
<li>Also <a href="https://www.youtube.com/watch?v=eTZ4VUZHzxw&amp;list=PLqzoL9-eJTNACQzVDW7ZhoKrveh4-mXv7&amp;index=3">this youtube video</a> provides a simple explanation of regression diagnostic plots.</li>
</ul>
</section>
<section id="exercises-1" class="level2">
<h2 class="anchored" data-anchor-id="exercises-1">Exercises 1</h2>
<p>Use the data sets from the World Value Survey and the European Value Study to formulate a hypothesis and conduct a multiple linear regression analysis to either support or reject it. The model should include one dependent variable, three independent variables and two control variables (typically demographic variables such as gender and age), for a total of five predictors. Refer to the documentation to identify the variables, and utilize the provided code to generate the data set. Ensure to thoroughly examine the variables and consult the documentation to accurately interpret the variable values (i.e., to check what a high value corresponds to and what a low value corresponds to).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Code to create a dataset "df" that includes the desired variable ####</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the full dataset: ZA7505_v4_0_0</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>ZA7505_v4_0_0 <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/ZA7505_v4-0-0.dta"</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create the research dataset "df" </span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> ZA7505_v4_0_0 <span class="sc">%&gt;%</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep Austrian data only</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cntry_AN <span class="sc">==</span> <span class="st">"AT"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># write here the codes of the variables you have choosen </span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, cntry_AN, X003, X003R, A006, A065, E033, A124_09, D081, F120, F121, F122, C001_01) <span class="sc">%&gt;%</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># you can choose to rename the selected columns. </span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If you prefer to work with variable codes cancel everything from "rename" to the pipe </span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># symbol "%&gt;%" after "F122"</span></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"Age"</span> <span class="ot">=</span> X003,</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Age recoded"</span> <span class="ot">=</span> X003R,</span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Important in life: Religion"</span> <span class="ot">=</span> A006,</span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Member: Belong to religious organization"</span> <span class="ot">=</span> A065,</span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Dont like as neighbours: homosexuals"</span> <span class="ot">=</span> A124_09,</span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Homosexual couples are as good parents as other couples"</span> <span class="ot">=</span> D081,</span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Jobs scarce: Men should have more right to a job than women"</span> <span class="ot">=</span> C001_01,</span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Self positioning in political scale"</span> <span class="ot">=</span> E033,</span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Justifiable: Abortion"</span> <span class="ot">=</span> F120,</span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Justifiable: Divorce"</span> <span class="ot">=</span> F121, </span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Justifiable: Euthanasia"</span> <span class="ot">=</span> F122) <span class="sc">%&gt;%</span></span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># clean the column names</span></span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">%&gt;%</span></span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep only positive values </span></span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_all</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> .x <span class="sc">&gt;=</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the case of this specific data set and data format, the values of the variables are labeled, and the labels can be accessed by using the <code>attributes</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(df<span class="sc">$</span>age_recoded)<span class="sc">$</span>labels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Missing: Other Not asked in survey      Not applicable           No answer 
                 -5                  -4                  -3                  -2 
         Don´t know               15-24               25-34               35-44 
                 -1                   1                   2                   3 
              45-54               55-64   65 and more years 
                  4                   5                   6 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(df<span class="sc">$</span>important_in_life_religion)<span class="sc">$</span>labels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Missing: Other  Not asked in survey       Not applicable 
                  -5                   -4                   -3 
           No answer           Don´t know       Very important 
                  -2                   -1                    1 
    Rather important   Not very important Not at all important 
                   2                    3                    4 </code></pre>
</div>
</div>
<p>Run the analysis and write a short report including:</p>
<ul>
<li><p>Formulation of the hypothesis (one hypothesis for each of the three independent variable, one sentence for each hypothesis).</p></li>
<li><p>Sample size of the data set, histogram of the dependent variable, and a table reporting the variables’ summary statistics (mean and standard deviations of the variables, minimum and maximum) when appropriate (i.e., for quantitative variables). For qualitative variables, report the frequencies (using the command <code>table</code> and <code>prop.table</code>: for example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># absolute frequencies</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>age_recoded)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6 
 72 192 212 254 211 314 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># relative frequencies</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>( <span class="fu">prop.table</span>(<span class="fu">table</span>(df<span class="sc">$</span>age_recoded)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6 
0.06 0.15 0.17 0.20 0.17 0.25 </code></pre>
</div>
</div></li>
<li><p>A multiple linear regression model to predict/explain your independent variable using dependent variables of your choice. Report the regression table and provide the appropriate interpretation.</p></li>
<li><p>Check out the diagnostic plots and provide an interpretation of the appropriateness of the linear model: do you see any evident pattern in the points? Are the dots grouped along a diagonal line in the normal Q-Q plot? Also calculate the Variance Inflation Factor (VIF) using the function <code>vif</code> function in the <code>car</code> package.</p></li>
</ul>
<p>Please use <code>Quarto Document</code> to create the report, as it includes the code and the output. The easiest way to create a nice report is to render to <code>html</code>. See <a href="https://quarto.org/docs/get-started/authoring/rstudio.html">this tutorial</a> to create a Quarto document, and copy the options to create a self-contained <code>html</code> report <a href="https://quarto.org/docs/output-formats/html-basics.html#self-contained">here</a>.</p>
<p>Report the findings using APA-style. For example:</p>
<blockquote class="blockquote">
<p>We tested if negative and positive emotions significantly predicted participants’ support for government, controlling for sex, age, and ideology. The results of the regression indicated the predictors explained 38.45% of the variance (Adj. R2 =.3845, F(5, 809) = 102.7, p &lt; .001). It was found that negative emotions significantly predicted participants’ support for government (<em>b</em> = .44, p &lt; .001), while positive emotions did not significantly predict participants’ support for government (<em>b</em> = -.027, p = .342).</p>
</blockquote>
<p>Also report the results of the regression model using a standard regression table. You can refer to any regression table published on a scientific journal (e.g., <a href="https://www.jstor.org/stable/pdf/2111665.pdf?casa_token=9O5i9dawIt0AAAAA:RXmgYQMt08Yj71j-Rbw9ThfmMIHSFJ_Jux_n_ewPQVjWkQYm6O98wYzdzi-6F76vGdukjJDN0uqaAl7w5VtGVGCOsVecT7lZMmDAfVdP4EGGQb6Hzs6E">p.&nbsp;970</a>), and also use the <code>stargazer</code> function in the homonym package for printing the table directly in the Quarto report.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"stargazer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can print and copy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(lm2, <span class="at">type=</span><span class="st">"text"</span>, <span class="at">style =</span> <span class="st">"apsr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------
                             govact         
--------------------------------------------
negemot                     0.441***        
                            (0.026)         
posemot                      -0.027         
                            (0.028)         
ideology                   -0.218***        
                            (0.027)         
sex                          -0.010         
                            (0.077)         
age                          -0.001         
                            (0.002)         
Constant                    4.064***        
                            (0.205)         
N                             815           
R2                           0.388          
Adjusted R2                  0.385          
Residual Std. Error     1.067 (df = 809)    
F Statistic         102.717*** (df = 5; 809)
--------------------------------------------
*p &lt; .1; **p &lt; .05; ***p &lt; .01              </code></pre>
</div>
</div>
</section>
<section id="exercises-2-optional" class="level2">
<h2 class="anchored" data-anchor-id="exercises-2-optional">Exercises 2 (optional)</h2>
<p>The following exercise is based on the <code>estress</code> data set (<code>estress.csv</code>).</p>
<section id="description-of-the-data-set" class="level3">
<h3 class="anchored" data-anchor-id="description-of-the-data-set">Description of the data set</h3>
<p>The participants in the <code>estress</code> study (162 male, 100 female, <code>sex</code> in the data, 0 = female, 1 = male) were asked a series of questions about how they felt their business was doing.</p>
<p>Their responses were used to construct an index of economic stress (<code>estress</code> in the data set, with high scores reflecting greater economic stress).</p>
<p>They were also asked the extent to which they had various feelings related to their business, such as “discouraged,” “hopeless,” “worthless,” and the like, an aggregation of which was used to quantify business-related depressed affect (<code>affect</code> in the data set, with higher scores reflecting more depressed affect).</p>
<p>They were also asked a set of questions to quantify their intentions to withdraw from entrepreneurship in the next year (<code>withdraw</code> in the data set, with higher scores indicative of greater withdrawal intentions).</p>
<p>There is also a measure of entrepreneurial self-efficacy which indexes a person’s confidence in his or her ability to successfully engage in various entrepreneurship-related tasks such as setting and meeting goals, creating new products, managing risk, and making decisions (<code>ese</code> in the data set).</p>
<p>The data set also includes the length of time in the business, in years (<code>tenure</code> in the data set), and the age of these entrepreneurs (<code>age</code>).</p>
</section>
<section id="exercise" class="level3">
<h3 class="anchored" data-anchor-id="exercise">Exercise</h3>
<p>Using the <code>estress</code> data set, write a short data analysis report including:</p>
<ul>
<li><p>Summary statistics: five number summary, standard deviation, and the sample size of the data set.</p></li>
<li><p>A multiple linear regression model to predict/explain <code>withdraw</code> intention based on the following independent variables: <code>affect</code>, <code>sex</code>, <code>estress</code>, <code>age</code>, <code>tenure</code>, <code>ese</code>. Report the regression table and provide the appropriate interpretation.</p></li>
<li><p>Check out the diagnostic plots and provide an interpretation: do you see any evident pattern in the points? Are the dots grouped along a diagonal line in the normal Q-Q plot? Also calculate the Variance Inflation Factor (VIF) using the function <code>vif</code> function in the <code>car</code> package.</p></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="//EDA.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Exploratory Data Analysis</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="//regression.html" class="pagination-link">
        <span class="nav-page-text">Regression analysis</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Nicola Righetti</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.nicolarighetti.net">
      <i class="bi bi-wordpress" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nicolarighetti">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://mas.to/@nicolarighetti">
      <i class="bi bi-mastodon" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/nicolarighetti79/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>